---
# yaml-language-server: $schema=https://kubernetes-schemas.haraldkoch.ca/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: tplink-plug-exporter
spec:
  groups:
    - name: tplink-plugexporter.rules
      rules: []
---
# yaml-language-server: $schema=https://kubernetes-schemas.haraldkoch.ca/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: tplink-plug-exporter
    prometheus: kube-prometheus
  name: tplink-plug-exporter-k8s
spec:
  endpoints:
    - interval: 30s
      metricRelabelings:
        - action: replace
          replacement: k8s
          sourceLabels:
            - instance
          targetLabel: instance
        - action: replace
          replacement: kp-125m-rack
          sourceLabels:
            - target
          targetLabel: target
      params:
        target:
          - 192.168.2.120
      path: /scrape
      port: metrics
      scheme: http
      scrapeTimeout: 30s
  jobLabel: tplink-plug-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/instance: tplink-plug-exporter
      app.kubernetes.io/name: tplink-plug-exporter
---
# yaml-language-server: $schema=https://kubernetes-schemas.haraldkoch.ca/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: internet
    app.kubernetes.io/name: tplink-plug-exporter
    prometheus: kube-prometheus
  name: tplink-plug-exporter-internet
spec:
  endpoints:
    - interval: 30s
      metricRelabelings:
        - action: replace
          replacement: internet
          sourceLabels:
            - instance
          targetLabel: instance
        - action: replace
          replacement: kp125m-spare
          sourceLabels:
            - target
          targetLabel: target
      params:
        target:
          - 192.168.2.121
      path: /scrape
      port: metrics
      scheme: http
      scrapeTimeout: 30s
  jobLabel: tplink-plug-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/instance: tplink-plug-exporter
      app.kubernetes.io/name: tplink-plug-exporter
