apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:xxnbfu67wgLvZ0PqTcNN0Q==,iv:LasA5aqx6l471zjQEEVJuPHGUWr+meE1DKMask3+Zb4=,tag:hgtvtQXcoMaInOpBa++mgw==,type:comment]
    SECRET_DOMAIN: ENC[AES256_GCM,data:Sztn9a9HEIs=,iv:RGf039nYAKBxuLPUNoeYExqQTADZpbgwDlrGrEFaO6Q=,tag:fn24DtiZKd+TILHIMGJ4YQ==,type:str]
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:WP62cGEnpolG,iv:g1rRgWcN1kGrlH0Mik0KPphQBq4cwthxUjAIj/lL7Fc=,tag:3JZzkpJ/erZ6BtCdWtVnDg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:olHOkyyRYoJsPRX3Rw==,iv:odKhYForOw05FJ2gxuleIpXFEDLBCiFpI5F5QZjZIvk=,tag:ypV4xi3YGbKjGu+sezpmHQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:T1MjNF1zdwsI1LpTkKsJADovUXCsHoKTI3sYcvoJOy01ZmpY,iv:utn/W/euk6A3GdPEaLaH4sWw7qKydHgnuIXkIk2CcMs=,tag:xyad2JjnpzNzyPTAIwvRrA==,type:str]
    K8S_GW: ENC[AES256_GCM,data:kxtISRLZtKLTt6A=,iv:y/0Z1wIIXDWgmHhDma2kAbG84vtPZ2jo0fYrkWhzyGc=,tag:+fRtwYCZ7gGvCi1mp3aRSQ==,type:str]
    SVC_NGINX_INTERNAL: ENC[AES256_GCM,data:ilfw6QhaTh0U7UU=,iv:eJ7/LGu8IZZjWJvDcl0DCAiavC8gf0gO8MTyQ04q3Ck=,tag:Feg8UOuivAv2gyeSh4OuCA==,type:str]
    SVC_NGINX_EXTERNAL: ENC[AES256_GCM,data:EEnrrSfroxhmdK0=,iv:A2CoFRYWGqyWYD/825xZ62Ppl9Rd1fAdDTC1iIoCFEE=,tag:DBn3cz0JIFxlbQILnLoegw==,type:str]
    SVC_HOME_ASSISTANT_ADDR: ENC[AES256_GCM,data:KlS7OuwdThCf8qg=,iv:Tv51Qc+2q2jmm83YfpKwcqJCOVap9WACE7yTrpvr9h0=,tag:Sk7GdOaHC9NORZIGsxlCxg==,type:str]
    SVC_MQTT_ADDR: ENC[AES256_GCM,data:JLe9yBBRNm4rQ3Y=,iv:35bLdpiBgXNeWPMYpAY6ehGBQVeZh3HZpMMyzXeqq0I=,tag:AaH6B2ycs0ZZARXGaYuu+g==,type:str]
    #ENC[AES256_GCM,data:BPZWwYV+Wj46jGSd,iv:ss4g5zPdAyMabOrb8qbvRVVoSTCKBRFgcZeDdQhOxWg=,tag:LKkxdQ5XwOZ7PLVJJm3dNA==,type:comment]
    SECONDARY_DOMAIN: ENC[AES256_GCM,data:x3NJl2d/bSBEFB04gMeiY+5IOQ==,iv:DTf9NRMwWg/kqz6h2oSVeQ8vHrCAlA7HrFodfywPEqE=,tag:oZrbtSst5ueLCXkp6Vk5Vg==,type:str]
    OLD_DOMAIN: ENC[AES256_GCM,data:z3ar+K3V4Q==,iv:sB5MowViV2fTDpNblLsjRx7VNyytQBCHXMun1rkMTtE=,tag:XLd0TZ1+QUbtBM/NQNbS9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12v9uw8k6myrr49z9aq6jmcwa79aepu0p6p462nrv968qcae72pcspwldec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SnlFNVh6cDhuaXdSdXg1
            a2IwUXFvejRQc2Z6NlR4ak5pdWJ5Q1JtU3pjCldleml5RXA4Tk5wc3VQZW5kNXlm
            enpieDhJL3dUQkxKQ2hKVldiTFhGa2MKLS0tIFV2ZWFJTGVodmNhS0FUQzZMbExY
            ZjkzSGxlT1R6VHNHNDVNb3hBVzNVZ3MKMtBhVS0FKr6NWqv9S6mSOhjCDIdO3uNz
            OS9Qh8tX5J/s1ZH6z3/DNLWKonA6mccm1kH7jNQe/+w4ozYxa4me9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-23T14:41:05Z"
    mac: ENC[AES256_GCM,data:8LIq2EPe6uafKllX6gZUEZ9Ht31ct6NOwiUkaqBPmjiruLh02k/Zhzlfm3eidRsK566mwqJ8wC3iQ8ShvyyzrfZf+F3rcoxosj39lPY3QmxNGk74MlpbqebmffDAmTPlQcGjGAW8+dZjOuV2k5UYeiQnlgngw5lSf0kXO2zV5M8=,iv:k8l5QkCV5V5qVDVUl8Th7bt1aH1ZHemOhlMenxARNDQ=,tag:eTVYlN8VTKFCmt3MJF1G6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
