apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:Yez3npSQ29Agw0eAXQ==,iv:F/z5K9rFOTe93j2pR4N+8Ar5uUukPXctO3qT2m2c2Hw=,tag:hJcX0+ZmR0BBZRmr0YPs2Q==,type:comment]
    PRIMARY_DOMAIN: ENC[AES256_GCM,data:AzntkKmgT1I=,iv:iyjaEVkKzmp7BGj+XBz3n6ZPdhIpzykjFsDTFm1t+mU=,tag:kv06oLNp9shRLvMkAlkiMA==,type:str]
    #ENC[AES256_GCM,data:9r47k9pGw9n4m5M=,iv:2p1TKM9pJ0/vh1Bitk0FZqKpSkHY6Gn/xYybOLwcWbc=,tag:LW5xEUXdupS6Lb7fHwrw7g==,type:comment]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:olHOkyyRYoJsPRX3Rw==,iv:odKhYForOw05FJ2gxuleIpXFEDLBCiFpI5F5QZjZIvk=,tag:ypV4xi3YGbKjGu+sezpmHQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:T1MjNF1zdwsI1LpTkKsJADovUXCsHoKTI3sYcvoJOy01ZmpY,iv:utn/W/euk6A3GdPEaLaH4sWw7qKydHgnuIXkIk2CcMs=,tag:xyad2JjnpzNzyPTAIwvRrA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:pRZk4tr7AA==,iv:diQhMNY0K8YAOot8RzatiAUPKPg5Xc7s5N87L28S9OQ=,tag:Z/mMUZFsT85BgVTMcbEnRw==,type:str]
    K8S_GW: ENC[AES256_GCM,data:RdHKzJfYbn1bE+U=,iv:uTD/sBqt15KLUstsXGrPCNqSE4455u62WeAb2a3FY0M=,tag:4SO3XAnA9Gbf+n2Th7EYUA==,type:str]
    SVC_NGINX_INTERNAL: ENC[AES256_GCM,data:duLyLizkytHO9Lw=,iv:ygcQZ/ri5b0ZAKlVEeHDX01S+cKz93wsHSAg/VL52C8=,tag:kSsa0DOa3JRXpUcU+nlv5g==,type:str]
    SVC_NGINX_EXTERNAL: ENC[AES256_GCM,data:GqGKwN7jhWzCiNE=,iv:AWu0gKwWnSYfXMjBWGNEo6QyqbxVbEjkD0eLDnsJppw=,tag:s2hINjyvtGWStjuKjjau8w==,type:str]
    SVC_HOME_ASSISTANT_ADDR: ENC[AES256_GCM,data:o0P6+2jnmOUrucw=,iv:tQq/SLi6zYi6aJoYu718yn92KcjMJksQ7vTgVgzS63I=,tag:Gza8YqFMp5DJlPssEkSMdw==,type:str]
    SVC_MQTT_ADDR: ENC[AES256_GCM,data:mOhk+SJGPCKezwk=,iv:A95oljgW0yzxnkrHRoF8Qp3r0YJyXBSlrnMANPmaM0g=,tag:RxRAh75Gg3TjSz5a0V6hUg==,type:str]
    SVC_THANOS_ADDR: ENC[AES256_GCM,data:YzLbBdq3HYw+qCw=,iv:U3OvWSFBQ/IenqUGAldXqy8uBl6hmA/xMoBiX7xcRMc=,tag:yvfjz7YoP4tv5LZC2uu41g==,type:str]
    #ENC[AES256_GCM,data:BPZWwYV+Wj46jGSd,iv:ss4g5zPdAyMabOrb8qbvRVVoSTCKBRFgcZeDdQhOxWg=,tag:LKkxdQ5XwOZ7PLVJJm3dNA==,type:comment]
    AUTH0_OMNI: ENC[AES256_GCM,data:gxg0I5kuMOvt56n1uxpulDQuGtfBD/QjRUe2isDR1dKS,iv:60+uncAdiPZOFahV8B22B3/1eYBlmnQXyoFguYLrM9g=,tag:5k00RsP9JY/GKEnZa/qlLQ==,type:str]
    PI_IP: ENC[AES256_GCM,data:guD8/HThumt0GmE=,iv:roZ3vhJbh04Uz3wz3oyhxTFwM2qDF63CA8DNp85lbN0=,tag:f8qApIas9rSC6Ij1DqNRAg==,type:str]
    NAS_IP: ENC[AES256_GCM,data:QP9qn+/I7eGzkPc=,iv:bZZ6hleWIYyutBbUNx8506DqHu8sbgbdMtd+yqEwXvQ=,tag:aslSsBLBUHaySZjS4HgTQg==,type:str]
    BEE_IP: ENC[AES256_GCM,data:0TlDrCw9ByQZuqg=,iv:VrpXJLADYCnrmkshKQS6oKhTeB2V7hIqj9k4d3qXfFA=,tag:TPLWNuGDWLv7PLUqdfiu2A==,type:str]
    SECONDARY_DOMAIN: ENC[AES256_GCM,data:x3NJl2d/bSBEFB04gMeiY+5IOQ==,iv:DTf9NRMwWg/kqz6h2oSVeQ8vHrCAlA7HrFodfywPEqE=,tag:oZrbtSst5ueLCXkp6Vk5Vg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12v9uw8k6myrr49z9aq6jmcwa79aepu0p6p462nrv968qcae72pcspwldec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SnlFNVh6cDhuaXdSdXg1
            a2IwUXFvejRQc2Z6NlR4ak5pdWJ5Q1JtU3pjCldleml5RXA4Tk5wc3VQZW5kNXlm
            enpieDhJL3dUQkxKQ2hKVldiTFhGa2MKLS0tIFV2ZWFJTGVodmNhS0FUQzZMbExY
            ZjkzSGxlT1R6VHNHNDVNb3hBVzNVZ3MKMtBhVS0FKr6NWqv9S6mSOhjCDIdO3uNz
            OS9Qh8tX5J/s1ZH6z3/DNLWKonA6mccm1kH7jNQe/+w4ozYxa4me9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-08T02:03:34Z"
    mac: ENC[AES256_GCM,data:koVpG7FyUdt9pTZi2WSmxmVXdGc2UTKRSKAoUDLMuG5zhdf5vxyD44EgeqJrG0Bd6ISfJmncniKaUqziBx+Ity1xwsnD1/vkegYzyeObBxTw3uLWk0aNFFDI0yGnokRpr4c37O5vxEfzXLX5kBJMLwDuuUpPUlOSnmFhkGcwdj0=,iv:aaw6drCcCtfO252zUozqWM7Akw91yxMaBegxYc9vtqY=,tag:nv2XFBzVbEEmBuXR3E+psA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
