---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app prowlarr
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../../shared/components/gatus/guarded
  dependsOn:
    - name: crunchy-postgres-cluster
    - name: crunchy-postgres-stores
    - name: onepassword-store
  interval: 30m
  path: ./kubernetes/main/apps/downloads/prowlarr/app
  postBuild:
    substitute:
      APP: *app
  prune: false # revert to true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: downloads
  timeout: 5m
  wait: false
