---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./mc-dns.yaml
  - ./nas-ingress.yaml
  - ./portainer-ingress.yaml
  - ./vpn-endpoint.yaml
