apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: palworld
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        SERVER_PASSWORD: "{{ .SERVER_PASSWORD }}"
        ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
        WEBHOOK_URL: "{{ .DISCORD_WEBHOOK }}"
  data:
  - secretKey: SERVER_PASSWORD
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: 14a164a2-87a1-42be-bb0e-b102004b0dab
      property: server_password
  - secretKey: ADMIN_PASSWORD
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: 14a164a2-87a1-42be-bb0e-b102004b0dab
      property: admin_password
  - secretKey: DISCORD_WEBHOOK
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: 14a164a2-87a1-42be-bb0e-b102004b0dab
      property: discord_webhook
