---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name palworld-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        SERVER_PASSWORD: "{{ .SERVER_PASSWORD }}"
        ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
        WEBHOOK_URL: "{{ .DISCORD_WEBHOOK }}"
  dataFrom:
  - extract:
      key: palworld
