# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app palworld
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
  - name: rook-ceph-cluster
    namespace: rook-ceph
  - name: volsync
    namespace: storage
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/jammsen/docker-palworld-dedicated-server
              tag: master@sha256:832fdfa9ae62e205be88854214d929e5b955e28be6b3f15c43c0e666281979cc
            env:
              ## Container Settings
              TZ: ${TIMEZONE}
              ALWAYS_UPDATE_ON_START: true
              MULTITHREAD_ENABLED: true
              COMMUNITY_SERVER: false
              BACKUP_ENABLED: false #volsync is backing up the PVC
              SERVER_SETTINGS_MODE: auto
              ## Server Gameplay Settings
              DEATH_PENALTY: None
              BASE_CAMP_WORKER_MAXNUM: 20
              PAL_EGG_DEFAULT_HATCHING_TIME: "2.000000" #Default for Normal Mode
              ## Server Settings
              SERVER_NAME: Platonically Pals
              SERVER_DESCRIPTION: Smurf's Palworld. Come in, have a tako!
              PUBLIC_PORT: &port 8211
              RCON_ENABLED: true
              RCON_PORT: &rcon-port 25575
              PUBLIC_IP: pal.${SECONDARY_DOMAIN}
              ## Webhook Settings
              WEBHOOK_ENABLED: true
            envFrom:
            - secretRef:
                name: palworld-secret
            probes:
              liveness: &disabled
                enabled: false
              readiness: *disabled
              startup: *disabled
            resources:
              requests:
                cpu: 1000m
              limits:
                memory: 24Gi
          exporter:
            image:
              repository: docker.io/bostrt/palworld-exporter
              tag: v1.3.1
            env:
              ## Container Settings
              TZ: ${TIMEZONE}
              RCON_HOST: localhost
              RCON_PORT: *rcon-port
              SAVE_DIRECTORY: /palworld
            envFrom:
            - secretRef:
                name: palworld-secret
            resources:
              limits:
                memory: 256Mi
              requests:
                cpu: 5m
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
        # pod:
        #   securityContext:
        #     runAsUser: 1000
        #     runAsGroup: 1000
        #     fsGroup: 1000
        #     fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: "${SVC_PALWORLD_ADDR}"
        ports:
          http:
            port: 9877
          game:
            protocol: UDP
            port: *port
          rcon:
            port: *rcon-port
    serviceMonitor:
      main:
        enabled: true
    ingress:
      main:
        enabled: false #nginx doesn't support non-https
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: ipv4.${SECONDARY_DOMAIN}
        hosts:
        - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
          paths:
          - path: /
            service:
              name: main
              port: game
        tls:
        - hosts:
          - *host
    persistence:
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
        - path: /palworld
      cache:
        config:
        enabled: true
        existingClaim: palworld-cache
        globalMounts:
          - path: /palworld/Pal/Binaries
            subPath: binaries
          - path: /palworld/Pal/Content
            subPath: content
      tmp:
        type: emptyDir
