# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app palworld
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
  - name: rook-ceph-cluster
    namespace: rook-ceph
  - name: volsync
    namespace: storage
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: jammsen/palworld-dedicated-server
              tag: 7afab27
            env:
              TZ: ${TIMEZONE}
              ALWAYS_UPDATE_ON_START: true
              MAX_PLAYERS: 32
              MULTITHREAD_ENABLED: true
              COMMUNITY_SERVER: false
              RCON_ENABLED: true
              RCON_PORT: 25575
              PUBLIC_PORT: 8211
              PUBLIC_IP: palworld.${SECRET_SECONDARY_DOMAIN}
              SERVER_NAME: LDS-Palworld-Server
              SERVER_DESCRIPTION: Palworld Server Running on Kubernetes
              BACKUP_ENABLED: false #volsync is backing up the PVC
              ## Server Gameplay Settings
              BASE_CAMP_WORKER_MAXNUM: "20"
              DEATH_PENALTY: "None"
              PAL_EGG_DEFAULT_HATCHING_TIME: "2.000000" #Default for Normal Mode
            envFrom:
            - secretRef:
                name: *app
            probes:
              liveness: &disabled
                enabled: false
              readiness: *disabled
              startup: *disabled
            resources:
              requests:
                cpu: 1000m
              limits:
                memory: 20Gi
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: "${SVC_PALWORLD_ADDR}"
        ports:
          http:
            enabled: false
          game:
            protocol: UDP
            port: 8211
          rcon:
            port: 25575
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: ipv4.${SECRET_SECONDARY_DOMAIN}
        hosts:
        - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
          paths:
          - path: /
            service:
              name: main
              port: game
        tls:
        - hosts:
          - *host
    persistence:
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
        - path: /palworld
