---
kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: homelab
spec:
  module: icmp
  prober:
    url: blackbox-exporter.observability.svc.cluster.local.:9115
  targets:
    staticConfig:
      static:
        - ${UNIFI_CONTROLLER_IP}
        - ${NAS_IP}
        - ${PI_IP}
