# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: minio-bitwarden-cli
stringData:
    bw_password: ENC[AES256_GCM,data:NZo62l+oMHLh,iv:+uz2gVtg3tdLtSDOUeUvbeX+Q6cubh3KydZ/aHq+zAw=,tag:Py7PzdP4w8CMU2vFcNCZkQ==,type:str]
    bw_client_id: ENC[AES256_GCM,data:VpoecxZXUysK5ocT0peiWp/HUyce5iVLx/UDGFhxN+k9xPJWgOWRd9M=,iv:tubgCeElJRK7KsDpEhdGGtxzjf9+CHyHC2SqW6ajWSw=,tag:rKsIvMj9Rg+SPFmgOkqXTA==,type:str]
    bw_client_secret: ENC[AES256_GCM,data:JUlgJL6nDdOCrF2l1spBj4n3eAguizCB9yhSTaBg,iv:bYLojhl/Or6lBFs0aPdfhkIPc4Lnr5eDLxoBQLRULaA=,tag:cYrK5Nxq6ZoiCKPuaLSFww==,type:str]
    bw_email: ENC[AES256_GCM,data:vl3aRwsTs6e6icvXIFseptniDxVpiBY=,iv:X9pdGWrQqlXNsZF73Ti84HyhaBTzG+OFRtKD21TFZ0g=,tag:Zv+spTkN4u5aB2aB1mqJnw==,type:str]
    minio_url: ENC[AES256_GCM,data:4IYSFpeeB0jzTnLCwZ6SBIJhpgG1E8c+6N3MUYN71wwfxA17,iv:J6uImyGsjDig/NizglyML7yFRxClb2WmjKJmPU/dCb8=,tag:rPRFdlzO2FKx5k6tzTVNZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12v9uw8k6myrr49z9aq6jmcwa79aepu0p6p462nrv968qcae72pcspwldec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWVR4eGJYWUJ1V0F4Z2x0
            NW8wbFQrY1YxakY3RGtuQmozbFlyL0NqekVzCmZXNWFBdVg5RlBtdUp1dHVFWDlm
            ZVlGOXRjUGpJRm1rMzh1ck5BSVhadmsKLS0tIGVqeE5HUnZVczl4NkJmNEJ1NVoz
            KzRDbWFsVEpsalByQ1pKL2VsbHZuaTQKKQ+Ia4b12/kVhKvypUlf/riQuTQFh9zy
            T/Lp0g6o1eW7KoE+tFk9QgPGYLphyXn/iVNWpz+bMTXhcgFL0qTQZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-06T20:22:03Z"
    mac: ENC[AES256_GCM,data:xntUyvg5SM2RlLQaDdBZjJi06vyOLqYUpQkt/3VjDYLP575KRySSZziWuyDG+3ZGUwzkJmpSWmp5ClqZM8YNwsDVcDBWDXFMWnMxyDSStk4lNhYIoWYG1wPVFPGDGmJf+oWyjan2p8EsQ9NS8MqBunmy/R6dvszLqCF3nBA4Lzk=,iv:akO4UK+ppnwBDF1KiKTcUg4466LnXz5BYl+xI7SNOWw=,tag:5z6Ri39c4TOdoynuX+Ia4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: authentik-bitwarden-cli
stringData:
    cluster_domain: ENC[AES256_GCM,data:O/Xp92G+XhQ=,iv:l81khcSilN4yo6XQFUuy36f7eKSG8qnZ4u9nM96TD6o=,tag:Fj0XB4xeSlWuOHGs8lkoeg==,type:str]
    authentik_endpoint: ENC[AES256_GCM,data:YDpvrjk0GZQReAvtYVUUFGt75n6cwzekK44=,iv:sqbuqxjYj5jor8i3aFC7bml8w1m0R12ZB8/UGjAVQiw=,tag:528gZ1RgMqmvjkz77FN4Cg==,type:str]
    authentik_token: ENC[AES256_GCM,data:0LcOhIncd/BMNN381BH/WRPHiLDZLxRID9B3yhycg60doJnKADih1Y7YNjUGqMrRpO41/3ygL6+CXbaD,iv:+jLB1CU0PPGkUUreeQEMziE4W7DTTerqu/Og3eDTOpU=,tag:QwwhllWf0HSTr0YsgBKCqg==,type:str]
    discord_client_id: ENC[AES256_GCM,data:gF9BCWLaQOX1v2TUWdcaHMoXlg==,iv:+II3a8ArS0N7fdH4V6YDQwt4lEumgEWYtK3RW6fHLCo=,tag:KZyJ1nTIt3ooaC97Wj1GgQ==,type:str]
    discord_client_secret: ENC[AES256_GCM,data:QUoodTBBx6zmaU+jjuFxpkagOVdiLeCCbwr5BMduq9w=,iv:flCk7n7O1vb/lBDX+SsfUK7GeS/4W4IZmnJKkbdSPA8=,tag:w42tGQAaARsMQTTQINuJjA==,type:str]
    google_client_id: ENC[AES256_GCM,data:S2AX7dzZRxWlT3PwFWBb9Cmldg3NhTQAWuqBsm+AWfoItKv8i1Da05Q4V09wqZ1IegF+w76rRRwnHWkdOS/KzfU81RjMocw=,iv:RkxOS0eLbUsyZevsFj67yfvJ9RBMQQiX47B99WmULcA=,tag:06cyJqMDRdF8XvN84GaSkA==,type:str]
    google_client:secret: ENC[AES256_GCM,data:Vm4fLZazpHuxk8U0MFlRxC7P3AwmV5DqaiepNkkWhDBWhko=,iv:KMe56LXBNrRiSA4uRRRkqGI9CnOtRwhv+iJfztc+eig=,tag:eNfpcS1aEeaCmEhzjF72rg==,type:str]
    gitops_id: ENC[AES256_GCM,data:tJCYSBJe,iv:05UhoQ0Gql75OVjN5OxzMJi1j9umxkSmEzivee+EOrw=,tag:8DpBQQTaqh22vy01cREyYA==,type:str]
    gitops_secret: ENC[AES256_GCM,data:ya27ciNSu37mffuCJnlUzFsBJAIhUEzpUmGZ5HNH7qXbfTfYqxUs3N4sOWJb1Q+36GO6t9OWj4c9xG2jEQ6zrJcXqddMyiSjzW/eFHbnJINVHDRg,iv:si7OKZYuV32IHm21QWeEYoIHwRmXWvW8cUCFZAiOGhw=,tag:1iPLXnlTLNTzOxac+7go+Q==,type:str]
    grafana_id: ENC[AES256_GCM,data:Ka/xsrjyFA==,iv:2BhH1zHsVEEQxwMo1PFLLfdg9z6FlB9b7XEHh2uWvIU=,tag:kMm++I+JoWzZ9keIJSv0ww==,type:str]
    grafana_secret: ENC[AES256_GCM,data:shAOcGwu8vWFP9Csv8oL91JIYeM+iKwPLnBQGzGVy5MBqZi20vpvTptT8LytrECNiAtozjmGd7FjBA6QqPo6ny3ujGuqhAPJEOlxtjfkfzRgOCk=,iv:yJ8po4Zjmc0Tkw2J6MJUzp/N6z6RpA7JaeqcS+rJFM4=,tag:DdSMzEomIpTrfGKWqNpUOA==,type:str]
    portainer_id: ENC[AES256_GCM,data:xKbLxHgc/mTG,iv:S7RR6ZONoBxB4AchAMhhLdt2lXHIM51tXkDwHF3My2Y=,tag:/SdNfLmjjHT1g+vEp/AE+A==,type:str]
    portainer_secret: ENC[AES256_GCM,data:eR92lyW7rstnG5/mpH49ueQZswcpmUB+VQYW55em5VY2yGTKWjO+C1Wqkasqn1PGcuNTbx3ey/qQuq6oUDIJB9xop/xiuer5A1UHxsJEw/JNOkQMvJKKlDjx3iaTSxQl/XAHBZk5EhM=,iv:IJTAzH71pGHk6Z/nUycOP5vBIHIeAXKCsCmgn+fRtAI=,tag:g4Ai7rb/qapn/G2JixdQcA==,type:str]
    bazarr_username: ENC[AES256_GCM,data:3Ch7xjXGbw==,iv:vuy25auEfSGeHpTsVElTNCNqS0rdMbVhQgTTmR/ZJ6s=,tag:bARP4ucVrmlsRWEpXSXJDA==,type:str]
    bazarr_password: ENC[AES256_GCM,data:V42awa2SqRdgycCzR4GYdYwyrdr3jjzsNw==,iv:d880TCo5AuVSkztJCRCi8WBmjQob+v//Rw1TZZtxJmw=,tag:uToXk6hrP4XodOSc+Mt+KA==,type:str]
    overseerr_username: ENC[AES256_GCM,data:UEU8wtIMODhxdjg9XA==,iv:QfmHTPxPC+GKaWXDZXMI2TdI93K1Axs0e8Zyf8FUwKM=,tag:z5zd9dWFsrhBmAr6m/UDiw==,type:str]
    overseerr_password: ENC[AES256_GCM,data:RsX8B8Ghzc4ALtHjPR0MveppfT3c6nilvAuw,iv:dyytnGAQY3TeCqtYKHLzztcVhzGJ4Y2ndRkPxY03DE4=,tag:9U43f6SrYeixjZWdnuRqJw==,type:str]
    prowlarr_username: ENC[AES256_GCM,data:nHJiFtkefg==,iv:K5LFsKcb2hybmFuYP74C21HN7aGcNTRfX+5EMzFXVkE=,tag:x9SK1vDnY6StJ9I0EcNTug==,type:str]
    prowlarr_password: ENC[AES256_GCM,data:QvzHY3ZeTeUkiqDysjhol9L3BXDiyg==,iv:k7JDagWnpPKyoNRS4pVx8ESrn6DDzBScHJZu4+dvXvw=,tag:CQNR7jg6ljuYcYpkDmqxWQ==,type:str]
    qbittorrent_username: ENC[AES256_GCM,data:18jXiA0=,iv:1wubjXigZi2ePWk8XKZ2W2aTQD/GtLLxdd54ZHdQYxY=,tag:uckrNLjAoYVrKQZyrgm87g==,type:str]
    qbittorrent_password: ENC[AES256_GCM,data:x6E7k9O6OEueZxIbFlWXQd16,iv:Is8VY8cGDHPL+Kg/uUmqf1oqyl5ty05dIphvI0pzseE=,tag:1yy8Z09EHfWsahOJr1YzBg==,type:str]
    radarr_username: ENC[AES256_GCM,data:/QmM7zobgA==,iv:yHMcpQSQ4XLAHRT4FrVmFHCVpEgZ+T+QItMjOu2BVMc=,tag:ppISNJAhgqsK7nIKijI9LA==,type:str]
    radarr_password: ENC[AES256_GCM,data:VGff99YO4bBjfau3dlGlnKWQD6wWxuqc8esS,iv:utyRKbW5pmGb91LBbjBUogQneONrdzHrxhHeVrJ8/vs=,tag:LlLpjhRZPgSr6yj3u6ELSQ==,type:str]
    readarr_username: ENC[AES256_GCM,data:ct0354Z6rA==,iv:Wf7CfsnGLQMwBDzhrEaqK7aLIK3MMF5NmyLLiGvdOTI=,tag:XEovEv2lE2XSyJP4CbFjEA==,type:str]
    readarr_password: ENC[AES256_GCM,data:MUVrRCPMb+meL68Ok1l8YZneW6/dBUERgw==,iv:fIAmluDqYh9ra1CEq4WNussmLItNbfcJ/aW0IjpkCm0=,tag:rbOtKjQxoodDd8aMvfnFgw==,type:str]
    sabnzbd_username: ENC[AES256_GCM,data:VtpiNKg3gALQhvM=,iv:wPuVljuU7HdpgT96AU2A8UTZnDQtqfYH+0/SM3YLTzw=,tag:xXssKXBehmwFOaOlFXIQVQ==,type:str]
    sabnzbd_password: ENC[AES256_GCM,data:z7UsV2E5VF54wuQ=,iv:TBwSU/vNT4CA1yBmaBsSU+rsXfPlf1NRyBc6gCQscqw=,tag:8yBg42KwM6LdOApWL0xgzw==,type:str]
    sonarr_username: ENC[AES256_GCM,data:5nmV4Gov6w==,iv:c3Z09rix5Qyfjc20IDPmlIpIksye/XVHSPoCRj+mNQg=,tag:ztcH+Yf0b8+X8x09LQkc7w==,type:str]
    sonarr_password: ENC[AES256_GCM,data:2DNKP8H5rG9981chXkachMyS,iv:COqODy3Dt+zTqAfDkuSqjVgErvKudFkBMYAfcjyTjjI=,tag:7CvGmPtPZugNKW5cwdm1bg==,type:str]
    tautulli_username: ENC[AES256_GCM,data:aP0RwzXY2g==,iv:ZnBbA3/TjjMaYIR6UdwIX7LWzLcUI4obHB0gd34NedA=,tag:TMZaeDs8KGjbq69W296yNw==,type:str]
    tautulli_password: ENC[AES256_GCM,data:0bmx8iIH+HPhr3HfK45XFvGWcchu,iv:z9ExQue7TJS3RGEdP/ekEhAVjsz+rwzvmz4dC2Wu948=,tag:QaiBYcjUYQDGIcek6cXrhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12v9uw8k6myrr49z9aq6jmcwa79aepu0p6p462nrv968qcae72pcspwldec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWVR4eGJYWUJ1V0F4Z2x0
            NW8wbFQrY1YxakY3RGtuQmozbFlyL0NqekVzCmZXNWFBdVg5RlBtdUp1dHVFWDlm
            ZVlGOXRjUGpJRm1rMzh1ck5BSVhadmsKLS0tIGVqeE5HUnZVczl4NkJmNEJ1NVoz
            KzRDbWFsVEpsalByQ1pKL2VsbHZuaTQKKQ+Ia4b12/kVhKvypUlf/riQuTQFh9zy
            T/Lp0g6o1eW7KoE+tFk9QgPGYLphyXn/iVNWpz+bMTXhcgFL0qTQZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-06T20:22:03Z"
    mac: ENC[AES256_GCM,data:xntUyvg5SM2RlLQaDdBZjJi06vyOLqYUpQkt/3VjDYLP575KRySSZziWuyDG+3ZGUwzkJmpSWmp5ClqZM8YNwsDVcDBWDXFMWnMxyDSStk4lNhYIoWYG1wPVFPGDGmJf+oWyjan2p8EsQ9NS8MqBunmy/R6dvszLqCF3nBA4Lzk=,iv:akO4UK+ppnwBDF1KiKTcUg4466LnXz5BYl+xI7SNOWw=,tag:5z6Ri39c4TOdoynuX+Ia4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
