---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app atuin
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  dependsOn:
    - name: crunchy-postgres-cluster
    - name: crunchy-postgres-stores
    - name: onepassword-store
  path: ./kubernetes/main/apps/self-hosted/atuin/app
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: sh
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: self-hosted
  timeout: 5m
  wait: false
