---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name lubelog-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        OpenIDConfig__Name: authentik
        OpenIDConfig__ClientId: "{{ .LUBELOG_CLIENT_ID }}"
        OpenIDConfig__ClientSecret: "{{ .LUBELOG_CLIENT_SECRET }}"
        OpenIDConfig__AuthURL: https://authentik.${SECRET_DOMAIN}/application/o/authorize/
        OpenIDConfig__TokenURL: https://authentik.${SECRET_DOMAIN}/application/o/token/
        OpenIDConfig__RedirectURL: https://lubelog.${SECRET_DOMAIN}/Login/RemoteAuth
        OpenIDConfig__Scope: openid,profile,email
  dataFrom:
  - extract:
      key: lubelog
