---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
data:
  ## Utility cluster settings
  CLUSTER: utility
  PVC_VOLSYNC_STORAGECLASS: local-hostpath
  VOLSYNC_SNAPSHOTCLASS: csi-local-hostpath
  VOLSYNC_CACHE_SNAPSHOTCLASS: local-hostpath
  VOLSYNC_STORAGECLASS: local-hostpath
