---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.1.0/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app your-spotify
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      server:
        enabled: true
        type: deployment
        strategy: &strategy RollingUpdate
        rollingUpdate: &rollingUpdate
          unavailable: 0
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: yooooomi/your_spotify_server
              tag: 1.11.0
            env:
              TIMEZONE: ${TIMEZONE}
              API_ENDPOINT: &api_endpoint https://spotty.${SECRET_DOMAIN}/api
              CLIENT_ENDPOINT: https://spotty.${SECRET_DOMAIN}
              MONGO_ENDPOINT: mongodb://your-spotify-mongodb:27017/your_spotify #mongo sucks
            envFrom:
              - secretRef:
                  name: your-spotify-secret
            probes: &probes
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            securityContext: &securityContext
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: {drop: ['ALL']}
            resources:
              requests:
                cpu: 10m
                memory: 550Mi
              limits:
                memory: 775Mi
      web:
        strategy: *strategy
        rollingUpdate: *rollingUpdate
        containers:
          app:
            image:
              repository: yooooomi/your_spotify_client
              tag: 1.11.0
            env:
              API_ENDPOINT: *api_endpoint
            probes: *probes
            securityContext: *securityContext
      mongodb: #mongo still sucks
        type: statefulset
        rollingUpdate: *rollingUpdate
        statefulset:
          podManagementPolicy: OrderedReady
        containers:
          app:
            image:
              repository: docker.io/library/mongo
              tag: 6.0.4-focal
            probes: *probes
    service:
      server:
        controller: server
        nameOverride: server
        primary: true
        ports:
          http:
            port: 8080
      web:
        controller: web
        nameOverride: web
        ports:
          http:
            port: 3000
      mongodb:
        controller: mongodb
        nameOverride: mongodb
        ports:
          http:
            port: 27017
    ingress:
      external:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        hosts:
          - host: spotty.${SECRET_DOMAIN}
            paths:
              - path: /?(.*)
                pathType: Prefix
                service:
                  identifier: web
                  port: http
              - path: /api/?(.*)
                pathType: Prefix
                service:
                  identifier: server
                  port: http
    persistence:
      config:
        existingClaim: *app
        advancedMounts:
          mongodb:
            app:
              - path: /data
