---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volsync-nfs-{{ .Release.Namespace }}
spec:
  capacity:
    storage: 1Mi
  accessModes: ["ReadWriteMany"]
  nfs:
    server: voyager.internal
    path: ${SECRET_NFS_VOLSYNC}
  mountOptions:
    - nfsvers=4.2
    - hard
    - noatime
    - nodiratime
    - rsize=131072
    - wsize=131072
    - nconnect=8
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volsync-nfs-{{ .Release.Namespace }}
spec:
  accessModes: ["ReadWriteMany"]
  volumeName: volsync-nfs-{{ .Release.Namespace }}
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
