# yaml-language-server: $schema=https://kube-schemas.pages.dev/infra.contrib.fluxcd.io/terraform_v1alpha2.json
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: minio
spec:
  interval: 12h
  approvePlan: auto
  backendConfigsFrom:
  - kind: Secret
    name: terraform-backend-secret
  path: ./minio
  sourceRef:
    kind: OCIRepository
    name: terraform
    namespace: flux-system
  varsFrom:
  - kind: Secret
    name: terraform-secret
