---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: terraform-backend-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      type: Opaque
      data:
        access_key: "{{ .access_key }}"
        secret_key: "{{ .secret_key }}"
        endpoint: "{{ .endpoint }}"
  data:
    - secretKey: access_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 5a98804c-6c54-4e09-817e-afd8012c70ad
        property: access_key
    - secretKey: secret_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 5a98804c-6c54-4e09-817e-afd8012c70ad
        property: secret_key
    - secretKey: endpoint
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 5a98804c-6c54-4e09-817e-afd8012c70ad
        property: endpoint
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: terraform-authentik-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      type: Opaque
      data:
        cluster_domain: ${SECRET_DOMAIN}
        authentik_token: "{{ .authentik_token }}"
        discord_client_id: "{{ .discord_client_id }}"
        discord_client_secret: "{{ .discord_client_secret }}"
        gitops_id: "{{ .gitops_id }}"
        gitops_secret: "{{ .gitops_secret }}"
        grafana_id: "{{ .grafana_id }}"
        grafana_secret: "{{ .grafana_secret }}"
        portainer_id: "{{ .portainer_id }}"
        portainer_secret: "{{ .portainer_secret }}"
        # bazarr_username: placeholder
        # bazarr_password: placeholder
        # overseerr_username: placeholder
        # overseerr_password: placeholder
        # prowlarr_username: placeholder
        # prowlarr_password: placeholder
        # qbittorrent_username: placeholder
        # qbittorrent_password: placeholder
        # radarr_username: placeholder
        # radarr_password: placeholder
        # readarr_username: placeholder
        # readarr_password: placeholder
        # sabnzbd_username: placeholder
        # sabnzbd_password: placeholder
        # sonarr_username: placeholder
        # sonarr_password: placeholder
        # tautulli_username: placeholder
        # tautulli_password: placeholder
  data:
    - secretKey: authentik_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 3ff34fd7-ec65-436c-865c-afcf0104ce37
        property: token
    - secretKey: discord_client_id
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 01af241c-b129-4560-877a-ac6e00f706e3
        property: authentik_client_id
    - secretKey: discord_client_secret
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 01af241c-b129-4560-877a-ac6e00f706e3
        property: authentik_client_secret
    - secretKey: gitops_id
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 5e19532f-62a4-4cb8-bdfc-afd501029d14
        property: client_id
    - secretKey: gitops_secret
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 5e19532f-62a4-4cb8-bdfc-afd501029d14
        property: client_secret
    - secretKey: grafana_id
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b36a66be-7898-4003-902a-afc701166ed9
        property: client_id
    - secretKey: grafana_secret
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b36a66be-7898-4003-902a-afc701166ed9
        property: client_secret
    - secretKey: portainer_id
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 7b792cef-9d6d-48f1-9fe0-acfa010ac442
        property: client_id
    - secretKey: portainer_secret
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 7b792cef-9d6d-48f1-9fe0-acfa010ac442
        property: client_secret
