---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name terraform-backend-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        access_key: "{{ .AWS_ACCESS_KEY_ID }}"
        secret_key: "{{ .AWS_SECRET_ACCESS_KEY }}"
        endpoint: s3.${PI_DOMAIN}
  dataFrom:
  - extract:
      key: minio
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name terraform-authentik-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        cluster_domain: ${SECRET_DOMAIN}
        authentik_token: "{{ .AUTHENTIK_TOKEN }}"
        discord_client_id: "{{ .DISCORD_CLIENT_ID }}"
        discord_client_secret: "{{ .DISCORD_CLIENT_SECRET }}"
        gitops_id: "{{ .GITOPS_CLIENT_ID }}"
        gitops_secret: "{{ .GITOPS_CLIENT_SECRET }}"
        grafana_id: "{{ .GRAFANA_CLIENT_ID }}"
        grafana_secret: "{{ .GRAFANA_CLIENT_SECRET }}"
        portainer_id: "{{ .PORTAINER_CLIENT_ID }}"
        portainer_secret: "{{ .PORTAINER_CLIENT_SECRET }}"
        paperless_id: "{{ .PAPERLESS_CLIENT_ID }}"
        paperless_secret: "{{ .PAPERLESS_CLIENT_SECRET }}"
  dataFrom:
  - extract:
      key: authentik
  - extract:
      key: discord
  - extract:
      key: grafana
  - extract:
      key: paperless
  - extract:
      key: portainer
  - extract:
      key: weave-gitops
