# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: terraform-minio-secret
stringData:
    bw_password: ENC[AES256_GCM,data:NZo62l+oMHLh,iv:+uz2gVtg3tdLtSDOUeUvbeX+Q6cubh3KydZ/aHq+zAw=,tag:Py7PzdP4w8CMU2vFcNCZkQ==,type:str]
    bw_client_id: ENC[AES256_GCM,data:VpoecxZXUysK5ocT0peiWp/HUyce5iVLx/UDGFhxN+k9xPJWgOWRd9M=,iv:tubgCeElJRK7KsDpEhdGGtxzjf9+CHyHC2SqW6ajWSw=,tag:rKsIvMj9Rg+SPFmgOkqXTA==,type:str]
    bw_client_secret: ENC[AES256_GCM,data:JUlgJL6nDdOCrF2l1spBj4n3eAguizCB9yhSTaBg,iv:bYLojhl/Or6lBFs0aPdfhkIPc4Lnr5eDLxoBQLRULaA=,tag:cYrK5Nxq6ZoiCKPuaLSFww==,type:str]
    bw_email: ENC[AES256_GCM,data:vl3aRwsTs6e6icvXIFseptniDxVpiBY=,iv:X9pdGWrQqlXNsZF73Ti84HyhaBTzG+OFRtKD21TFZ0g=,tag:Zv+spTkN4u5aB2aB1mqJnw==,type:str]
    minio_url: ENC[AES256_GCM,data:4IYSFpeeB0jzTnLCwZ6SBIJhpgG1E8c+6N3MUYN71wwfxA17,iv:J6uImyGsjDig/NizglyML7yFRxClb2WmjKJmPU/dCb8=,tag:rPRFdlzO2FKx5k6tzTVNZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12v9uw8k6myrr49z9aq6jmcwa79aepu0p6p462nrv968qcae72pcspwldec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWVR4eGJYWUJ1V0F4Z2x0
            NW8wbFQrY1YxakY3RGtuQmozbFlyL0NqekVzCmZXNWFBdVg5RlBtdUp1dHVFWDlm
            ZVlGOXRjUGpJRm1rMzh1ck5BSVhadmsKLS0tIGVqeE5HUnZVczl4NkJmNEJ1NVoz
            KzRDbWFsVEpsalByQ1pKL2VsbHZuaTQKKQ+Ia4b12/kVhKvypUlf/riQuTQFh9zy
            T/Lp0g6o1eW7KoE+tFk9QgPGYLphyXn/iVNWpz+bMTXhcgFL0qTQZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-06T21:20:42Z"
    mac: ENC[AES256_GCM,data:Ts2NlRckrDmWfFxcL3EQh/dQKjCRJpfFM4lV+/LrYgmOv7f77OMhLkTle+O++E3n7ksKHEuZekQwceEUoWDqH1z8uXlXK3MGP1uc4OeVTlNc78GYru12/ubDtUnYnbo5aAHsYNUdXd/fnA1FLIEqz0tfiZJ7HBWtwuOc9q322pI=,iv:iOz8suTv1mmjlTvMjsXLCw7LBaP+/RZKMaziyPvyn2o=,tag:xkMy5YBnDh229ADVLgwhfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
