---
# Area
area/ansible:
  - changed-files:
      - any-glob-to-any-file: ansible/**/*
area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**/*"
          - "README.md"
area/github:
  - changed-files:
      - any-glob-to-any-file: .github/**/*
area/kubernetes:
  - changed-files:
      - any-glob-to-any-file: kubernetes/**/*
area/taskfile:
  - changed-files:
      - any-glob-to-any-file:
          - ".taskfiles/**/*"
          - "Taskfile.yaml"
area/terraform:
  - changed-files:
      - any-glob-to-any-file: terraform/**/*
# Cluster
cluster/main:
  - changed-files:
      - any-glob-to-any-file: ansible/main/**/*
      - any-glob-to-any-file: kubernetes/main/**/*
      - any-glob-to-any-file: terraform/main/**/*
cluster/pi:
  - changed-files:
      - any-glob-to-any-file: ansible/pi/**/*
      - any-glob-to-any-file: kubernetes/pi/**/*
      - any-glob-to-any-file: terraform/pi/**/*
cluster/utility:
  - changed-files:
      - any-glob-to-any-file: ansible/utility/**/*
      - any-glob-to-any-file: kubernetes/utility/**/*
      - any-glob-to-any-file: terraform/utility/**/*
