---
# Area
area/ansible:
  - changed-files:
      - any-glob-to-any-file: ansible/**/*
area/docs:
  - changed-files:
      - any-glob-to-any-file: docs/**/*
      - any-glob-to-any-file: README.md
area/github:
  - changed-files:
      - any-glob-to-any-file: .github/**/*
area/kubernetes:
  - changed-files:
      - any-glob-to-any-file: kubernetes/**/*
area/taskfile:
  - changed-files:
      - any-glob-to-any-file: .taskfiles/**/*
      - any-glob-to-any-file: Taskfile*
area/terraform:
  - changed-files:
      - any-glob-to-any-file: terraform/**/*
# Cluster
cluster/teyvat:
  - changed-files:
      - any-glob-to-any-file: ansible/teyvat/**/*
      - any-glob-to-any-file: kubernetes/teyvat/**/*
      - any-glob-to-any-file: terraform/teyvat/**/*
cluster/pi:
  - changed-files:
      - any-glob-to-any-file: ansible/pi/**/*
      - any-glob-to-any-file: kubernetes/pi/**/*
      - any-glob-to-any-file: terraform/pi/**/*
