---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name dashbrr-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # App
        DASHBRR_RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
        DASHBRR_SONARR_API_KEY: "{{ .SONARR_API_KEY }}"
        DASHBRR_PROWLARR_API_KEY: "{{ .PROWLARR_API_KEY }}"
        DASHBRR_PLEX_API_KEY: "{{ .PLEX_API_KEY }}"
        # OIDC
        OIDC_ISSUER: "https://sso.${SECRET_DOMAIN}/application/o/dashbrr/"
        OIDC_CLIENT_ID: "{{ .DASHBRR_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .DASHBRR_CLIENT_SECRET }}"
        OIDC_REDIRECT_URL: "https://dashbrr.${SECRET_DOMAIN}/api/auth/callback"
  dataFrom:
  - extract:
      key: radarr
  - extract:
      key: sonarr
  - extract:
      key: prowlarr
  - extract:
      key: plex
  - extract:
      key: dashbrr
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name dashbrr-db-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: dashbrr-secret
    creationPolicy: Merge
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        DASHBRR__DB_TYPE: postgres
        DASHBRR__DB_NAME: '{{ .dbname }}'
        DASHBRR__DB_HOST: '{{ index . "pgbouncer-host" }}'
        DASHBRR__DB_PORT: '{{ index . "pgbouncer-port" }}'
        DASHBRR__DB_USER: '{{ .user }}'
        DASHBRR__DB_PASSWORD: '{{ .password }}'
  dataFrom:
  - extract:
      key: postgres-pguser-dashbrr
