---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

set: [pipefail]
shopt: [globstar]

vars:
  CLUSTER: '{{.CLUSTER | default "main"}}'
  CLUSTER_DIR: '{{.ROOT_DIR}}/kubernetes/{{.CLUSTER}}'
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"

env:
  GOPATH: '{{.ROOT_DIR}}/.go'
  KUBECONFIG: '{{.CLUSTER_DIR}}/kubeconfig'
  MINIJINJA_CONFIG_FILE: '{{.ROOT_DIR}}/.minijinja.toml'
  SOPS_AGE_KEY_FILE: '{{.ROOT_DIR}}/age.key'
  TALOSCONFIG: '{{.CLUSTER_DIR}}/talosconfig'
  VIRTUAL_ENV: '{{.ROOT_DIR}}/.venv'

includes:
  bootstrap: .taskfiles/bootstrap
  bitwarden: .taskfiles/bitwarden
  kubernetes: .taskfiles/kubernetes
  sops: .taskfiles/sops
  talos: .taskfiles/talos
  volsync: .taskfiles/volsync
  workstation: .taskfiles/workstation

tasks:

  default:
    cmd: task --list
    silent: true
