---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"

env:
  KUBECONFIG: "{{.KUBERNETES_DIR}}/kubernetes/main/kubeconfig:{{.KUBERNETES_DIR}}/kubernetes/pi/kubeconfig"
  SOPS_AGE_KEY_FILE: "{{.ROOT_DIR}}/age.key"

includes:
  ansible: .taskfiles/Ansible
  bitwarden: .taskfiles/Bitwarden
  external-secrets: .taskfiles/ExternalSecrets
  flux: .taskfiles/Flux
  kubernetes: .taskfiles/Kubernetes
  postgres: .taskfiles/Postgresql
  rook: .taskfiles/Rook
  sops: .taskfiles/Sops
  talos: .taskfiles/Talos
  volsync: .taskfiles/VolSync

tasks:

  default:
    silent: true
    cmd: task -l
