---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kustomize-mutating-webhook
spec:
  interval: 30m
  chart:
    spec:
      chart: kustomize-mutating-webhook
      version: 0.3.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: fluxcd-kustomize-mutating-webhook
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    replicaCount: 1
    certManager:
      enabled: true
    configMaps:
      - create: true
        name: cluster-settings
        data:
          CLUSTER: utility
          PVC_VOLSYNC_STORAGECLASS: local-hostpath
          VOLSYNC_SNAPSHOTCLASS: csi-local-hostpath
          VOLSYNC_CACHE_SNAPSHOTCLASS: local-hostpath
          VOLSYNC_STORAGECLASS: local-hostpath
    secrets:
      - name: sops-age
        optional: true
    podDisruptionBudget:
      enabled: false #single node cluster
