---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name crunchy-postgres
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        s3.conf: |
          [global]
          repo1-s3-key={{ .MINIO_POSTGRES_ACCESS_KEY }}
          repo1-s3-key-secret={{ .MINIO_POSTGRES_SECRET_KEY }}
          rpeo2-s3-key={{ .CLOUDFLARE_POSTGRES_ACCESS_KEY }}
          repo2-s3-key-secret={{ .CLOUDFLARE_POSTGRES_SECRET_KEY }}
  dataFrom:
    - extract:
        key: postgresql_bucket
