---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crunchy-postgres
spec:
  target:
    deletionPolicy: Delete
    template:
      metadata:
      data:
        s3.conf: |
          [global]
          repo1-s3-key={{ .MINIO_ACCESS_KEY }}
          repo1-s3-key-secret={{ .MINIO_SECRET_KEY }}
          rpeo2-s3-key={{ .R2_ACCESS_KEY }}
          repo2-s3-key-secret={{ .R2_SECRET_KEY }}
  data:
    - secretKey: MINIO_ACCESS_KEY
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: eff71b07-9389-4874-923b-b0560025ea51
        property: username
    - secretKey: MINIO_SECRET_KEY
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: eff71b07-9389-4874-923b-b0560025ea51
        property: password
    - secretKey: R2_ACCESS_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: fb121da5-ecd8-4e94-a5a0-b0fe011aef94
        property: r2_access_key_id
    - secretKey: R2_SECRET_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: fb121da5-ecd8-4e94-a5a0-b0fe011aef94
        property: r2_secret_key
