---
kubernetes:
  vars:
    ansible_user: vetrius
    ansible_ssh_port: 22
  children:
    master:
      hosts:
        navia:
          ansible_host: 192.168.1.50
        ganyu:
          ansible_host: 192.168.1.51
          ceph_drives:
            - /dev/disk/by-id/nvme-CT1000P3SSD8_2314E6C52009
        hutao:
          ansible_host: 192.168.1.52
          ceph_drives:
            - /dev/disk/by-id/nvme-WD_BLACK_SN770_1TB_230314800616
    worker:
      hosts:
        ayaka:
          ansible_host: 192.168.1.53
          ceph_drives:
            - /dev/disk/by-id/nvme-WD_BLACK_SN770_1TB_23026Y802292
        eula:
          ansible_host: 192.168.1.54
          ceph_drives:
            - /dev/disk/by-id/nvme-WD_BLACK_SN770_1TB_22501H800457
