---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app victoria-metrics
spec:
  interval: 30m
  chart:
    spec:
      chart: victoria-metrics-agent
      version: 0.10.9
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    replicaCount: 1
    deployment:
      enabled: true
    remoteWriteUrls:
      - https://victoria-metrics.${SECRET_DOMAIN}/insert/0/prometheus
    service:
      enabled: true
    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        external-dns.alpha.kubernetes.io/target: internal-utility.${SECRET_DOMAIN}
      hosts:
        - vmagent-utility.${SECRET_DOMAIN}
    config:
      global:
        scrape_interval: 30s
