---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: palworld-tools
spec:
  target:
    deletionPolicy: Delete
    template:
      engineVersion: v2
      type: Opaque
      data:
        rcon.yaml: |-
          ---
          palworld:
            address: "palworld.games.svc.cluster.local:25575"
            password: "{{ .ADMIN_PASSWORD }}"
  refreshInterval: 1h
  data:
    - secretKey: ADMIN_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 14a164a2-87a1-42be-bb0e-b102004b0dab
        property: admin_password
