---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name palworld-tools-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        rcon.yaml: |-
          ---
          palworld:
            address: "palworld.games.svc.cluster.local:25575"
            password: "{{ .ADMIN_PASSWORD }}"
  dataFrom:
  - extract:
      key: palworld
