---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
spec:
  interval: 30m
  chart:
    spec:
      chart: volsync
      version: 0.9.1
      sourceRef:
        kind: HelmRepository
        name: backube
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: snapshot-controller
      namespace: storage
  values:
    manageCRDs: true
    image: &image
      repository: ghcr.io/joryirving/volsync
      tag: 0.9.1@sha256:b18033a4d850ef98b95263dc97ca2fc453c4b98fc8cea45d18483417e56c4f16
    restic:
      <<: *image
    metrics:
      disableAuth: true
