apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:22kLRx961fV93eFXrw==,iv:vR8AYz5+5gOVT5/j6KXlI5ZaDkFtgNuNTUiyajWWjpg=,tag:z6SmHkEL69t9Hx6xgF/liA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:2ATU/FJzrTT9UYmJ8TNXlztdAKmb1B03nXZ92oQ3DUqB+soT,iv:fqCluZe9pDMF8/amCTzttRWGcbiUUYjE8pbRiFGA8KI=,tag:1TsssKRYBJHKG91oNFyDZQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:Ulc4QMnUa3g=,iv:wAJV0i1bjV+/grFguyaSE45+SXemSvmBbq5UIkeEO0Y=,tag:ae5kL99lzMxi8X1fTaTQLw==,type:str]
    CLUSTER_NAME: ENC[AES256_GCM,data:HXSlAA==,iv:6ZzOS05A2Wk6erUI3w5tSqgyL1JYvqUOorNOevmIN1c=,tag:PsadKrpMj6fCRcX5RTcfJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12v9uw8k6myrr49z9aq6jmcwa79aepu0p6p462nrv968qcae72pcspwldec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NWNTRmtma01pMFY3Ny93
            N2F5bTZFc0ZKYm5hWHp6bENndktxRXNBa1F3CnBNVXJldG9ZR0cwcXQrcjc5UTNu
            dlpJNEZ5eVhIdkwvRE5ubUNBQjhnWTQKLS0tIDhzRGZTdWFKak5PNmVnbG5hckl3
            Mml3TDJwa2tWTUV3d0piVTFJSFhhOEEKr0FLybpRsnIlbT55No+/qolp2GVAB1yD
            yeGYjULaarqScUazhWSnuzDcRj4X0MX8UDV5lc4OsGba9ymVbywDbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-18T20:48:53Z"
    mac: ENC[AES256_GCM,data:rE2R9XMYXTLOTIEw2zzckruH9DjQKuMrMe8rxnAzmlG/kY/uPkbTRU8Dbx38KqJK/ORS52xJEP3wLSPyXZm47w+Qb5tF9tBZgLCRm2LvsZ1eckdaiy8fW/Pf8L61dCz4AB4mtFnRu6vB1FPqSOCdtgZ2wZHr6nvDjyf1tnFwUO4=,iv:FhaWorCL2IubD0+mVaouRHrQT0lYHuBZexXM2oc2hnE=,tag:qAekrqRZ6liPZYzhdcydjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
