apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_SECONDARY_DOMAIN: ENC[AES256_GCM,data:YwdPr2YjI1JnxR0kHpW7QDSg5A==,iv:gPsAPRiEPLQITD53JlfrziCDm54vo6CIYyAHmM7+Jc0=,tag:2v2uhQgJwP77Gw1fxyIi7w==,type:str]
    SVC_HOME_ASSISTANT_ADDR: ENC[AES256_GCM,data:JJDdO2ul93g6g9GWGg==,iv:f7g8TI4wLGNfxLcgbCrdU8txIA86h8x3l84qdRcI4GY=,tag:Dc31QuHuPESh2cyq2nrogw==,type:str]
    SVC_DB_ADDR: ENC[AES256_GCM,data:IuuCIiAi5ZQJE/m5Yw==,iv:ECEy4uPBIf9TdCzVVVHwwsOrBBXF5uQG689RHrY0x5Y=,tag:+P1ba7w9XjqKC3epYrQN8g==,type:str]
    SVC_PLEX_ADDR: ENC[AES256_GCM,data:GS5mbGIQTRwVQXqO8A==,iv:6GiUA97PplXZhUwmG/pqEDmJvK427UcMjy4nfvL62/E=,tag:eRg7SqXUI0Ew6IYd8HHflQ==,type:str]
    SVC_QBITTTORENT_ADDR: ENC[AES256_GCM,data:PvUIvSn8gwmICXpd8g==,iv:2hOM+FB6LnSp+wjJANdaVbl4ArwFLOGWmp0TbzNP/ws=,tag:DJHILz+AarDSwinVMEICvw==,type:str]
    SVC_SYNCTHING_ADDR: ENC[AES256_GCM,data:ks2AA53Kg/3FWGe+8A==,iv:u9LrOyw5etEmXH1MmqqZvkzBCNXMemT8Fyjq+2l0iwE=,tag:oSTAYNtL6Uhj6IilvX1Eiw==,type:str]
    SVC_MQTT_ADDR: ENC[AES256_GCM,data:vXQmZ4lLPWG3gexzeg==,iv:hHQvybs8qtAExkNPqv47enohyGfu7J40xAwxo14GVkQ=,tag:lnlydUq+labOdscJpBkEeA==,type:str]
    SVC_MINECRAFT_ADDR: ENC[AES256_GCM,data:/3etL1xutu+O8cQfiw==,iv:GIAlGs0TZ86Be6Q3FY5QfqDgUGDczS5E8mpf+9QO5nU=,tag:HC3eZcztKEPhDFAbYxfftQ==,type:str]
    SVC_VECTOR_ADDR: ENC[AES256_GCM,data:NviRxb5eLKg3vjprOA==,iv:laN2Q61nEJI9CP0U5B3uEMR1Tm0G/QyZQunFTVMvnM8=,tag:cvEimGD/6gOZcpF/Aa7IoA==,type:str]
    SECRET_NFS_DATA: ENC[AES256_GCM,data:ObpEHYf6jTVNoCOH+eI=,iv:Vfa8i36E4I7akmQk87jxNYpap06sjzWXppLhWTAPffk=,tag:ZJ3jiTlwKNkyuVK4RPqtSg==,type:str]
    SECRET_NFS_MINIO: ENC[AES256_GCM,data:htt6rJrLZKaOpUW2q8+G,iv:YZc47JrKFTBGnt1XBCs1dgkaGTBTakz04/EctiFyoU8=,tag:RlRoTjuA7tqcFQ8bAVLAxw==,type:str]
    SECRET_NFS_PAPERLESS: ENC[AES256_GCM,data:m61LAv47V6Jz2Y6u1Psj,iv:1EuNxC08cR+ztlHUO6o+KoRBR5wiIbyGSPu43AptQkY=,tag:FNc3IZh4uHx4CKkm8MmZsA==,type:str]
    SECRET_NFS_POSTGRES: ENC[AES256_GCM,data:fQyg6esRhjChgNPcXO40EGhMABLWjrgitw==,iv:9D75bBROmU9c9Ed1im+s5prsHe9cbIYD1O/3pQsfUv0=,tag:OSuuKvF5x+rk9ePD0aIvuA==,type:str]
    SECRET_NFS_SYNCTHING: ENC[AES256_GCM,data:aLT/vWNfWaJGTdCH0Fy7NLUSIw==,iv:J3dDbkfTvYmHiJj/KE7F/f0BaGW+st5ihUMjLGAfRqE=,tag:vQO6SyCXH0girRFHq4Y/hw==,type:str]
    MINIO_TOKEN: ENC[AES256_GCM,data:oZ2RGEFNOCqV8Z8ZE1zDCOoCiU7eUpm/j8O4dFeQafOCR57GiijlcuECz4l7lY+Djjdg7F6WMmWAXO6r8RX1+8+x0KT+wYx03yLGkt7ZU1QswBxv1fBN06Hkiayb18o1r+WW8fxmwy17suUr3bOxGTozPVW6Xpl3bDrHSGoxgNOIMEd2p8uDqQdoAPUpYlXrZ9uQ7YOlWK51EMGywLHL4orM3peHmOHV04MusKQ83hNBag9xkfAtnDJVVlwfFW6pzLe1DpZbADvUW+A6lZc/,iv:dLEG2e9Ohw8J+ON+mlwpOr3IlwX2QLRfnEjcIVYPLDc=,tag:nTn2OhkA1fZ47hhYsqRb1Q==,type:str]
    NAS_IP: ENC[AES256_GCM,data:RrvryNXyKcilT6u43Q==,iv:0BYAxU5l9u64I3rrz+ESyQ98OPA6uWxINTySq/XFNvo=,tag:6z+EOhfMz8j6A2W7s5C9iQ==,type:str]
    PI_IP: ENC[AES256_GCM,data:32wgJboQFvEFWAJQeg==,iv:Ww0lFQf5vemL3AyP9BNcUFVSwIK8g0bIgnbcmdOyoZI=,tag:/UqwfTNbhWCnHTG8JB582g==,type:str]
    UNIFI_CONTROLLER_IP: ENC[AES256_GCM,data:huVNTj+A8b3gXJ4=,iv:kPlTAN2HvP2+sbvTlKtLgYAuLNlj9xrLB0bG1RQdw70=,tag:alPjOIZ+hqE4vBPepcd5Gg==,type:str]
    SECRET_VPN_FORWARDED_PORT_1: ENC[AES256_GCM,data:dzopgeI=,iv:Y5/ayKFUhPoMvfijhxY0pQVBZ0MkYpFtCDASyahYtms=,tag:Ofhxgb+Wm1RXb8YIgy9zUA==,type:str]
    LATITUDE: ENC[AES256_GCM,data:JdGI021A1+8bbeHM+lB4EA==,iv:dZyT6bQAMPD16iJXfOofRtVXTJ4ktPC8I1gg2SpHROQ=,tag:aV/U5oPsxIoJi1wf9b2edA==,type:str]
    LONGITUDE: ENC[AES256_GCM,data:Qlt3G0Ww/dIBYZMTUFxGMu8=,iv:FpuFuc9dr5jmYtyTWf2x2YmUuf998uQAL40ht4CCdM0=,tag:9mXJJW71ulyDVy+qtQ6Z3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12v9uw8k6myrr49z9aq6jmcwa79aepu0p6p462nrv968qcae72pcspwldec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQkhwdTFsWkpDeXptZ1Fo
            WmhESG94d2FCeDEzV3VWVU5tdWhTdXUreHo4CjJRQUh5RG0yWm9hcWtjWDhnWWVZ
            dGZER1RONEtwSkYzN2d1VTlJZW1DdG8KLS0tIHBwODZpdkY0Zkx6bGlYeHRpczlY
            MGJoaXU1a0dJMHZrMHNPdzFscUpMSUEKYPFTbA46ao5h9CkApwHwlahoRME2JbKW
            KZlhQW6NqTFDTJ66XSqHJJVD2aAOwm+fDqDihl+1xjQXClZLWlG/Zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-03T16:41:46Z"
    mac: ENC[AES256_GCM,data:UgJqv/2nXvoEM1C2hNBQVbR/E4y6Z2wC7bzqpSU4H6fv+uPJKaXkjJ5ZjRKKeMx7U1BW3/t+zxAxN4jwEW1hfEbYK92ngbQSF20JJDg3cwV7ANVn+oBrlbVM4EWKoXEotna8JwlY2YCjxBZa49+0FalsRQmf/iD689k+k+o9qaM=,iv:zuMwdt4ox9FoYqQIYJi+H75vBaGrFQhobAGzYp6qSFI=,tag:onaBifk2tiKHGFpTvy1vxg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
