---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app mc-router
  namespace: flux-system
spec:
  targetNamespace: games
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/main/apps/games/minecraft/mc-router
  prune: false # revert to true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false # no flux ks dependents
  interval: 30m
  timeout: 5m
# ---
# # yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &app minecraft-vibecraft
#   namespace: flux-system
# spec:
#   targetNamespace: games
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *app
#   dependsOn:
#     - name: external-secrets-stores
#   path: ./kubernetes/main/apps/games/minecraft/vibecraft
#   prune: false # revert to true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   wait: false # no flux ks dependents
#   interval: 30m
#   timeout: 5m
#   postBuild:
#     substitute:
#       APP: *app
#       VOLSYNC_CAPACITY: 15Gi
# ---
# # yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &app minecraft-create
#   namespace: flux-system
# spec:
#   targetNamespace: games
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *app
#   dependsOn:
#     - name: external-secrets-stores
#   path: ./kubernetes/main/apps/games/minecraft/create
#   prune: false # revert to true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   wait: false # no flux ks dependents
#   interval: 30m
#   timeout: 5m
#   postBuild:
#     substitute:
#       APP: *app
#       VOLSYNC_CAPACITY: 15Gi
# ---
# # yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &app minecraft-takocraft
#   namespace: flux-system
# spec:
#   targetNamespace: games
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *app
#   dependsOn:
#     - name: external-secrets-stores
#   path: ./kubernetes/main/apps/games/minecraft/takocraft
#   prune: false # revert to true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   wait: false # no flux ks dependents
#   interval: 30m
#   timeout: 5m
#   postBuild:
#     substitute:
#       APP: *app
#       VOLSYNC_CAPACITY: 15Gi
