---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sss-feedcord
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/lildrunkensmurf/feedcord
              tag: 1.3.0@sha256:9186e29500572270a2f3c98c850d06038353029aaece1fbd44f4bc8d181305ed
            env:
              TZ: ${TIMEZONE}
            probes:
              liveness: &disabled
                enabled: false
              readiness: *disabled
              startup: *disabled
            resources:
              requests:
                cpu: 5m
              limits:
                memory: 128M
    service:
      main: *disabled
    ingress:
      main: *disabled
    persistence:
      config:
        enabled: true
        type: secret
        name: sss-feedcord-secret
        globalMounts:
          - path: /app/config/appsettings.json
            subPath: appsettings.json
            readOnly: true
