---
version: "3"

vars:
  PYTHON_BIN: python3

env:
  BREWFILE: "{{.ROOT_DIR}}/.taskfiles/Ansible/Brewfile"

tasks:
  brew:
    desc: Install workstation dependencies with Brew
    cmd: brew bundle --file {{.BREWFILE}}
    preconditions:
      - { msg: "Missing Homebrew", sh: "command -v brew" }
      - { msg: "Missing Brewfile", sh: "test -f {{.BREWFILE}}" }
