---
web:
  port: ${CUSTOM_WEB_PORT}
metrics: true
debug: false
ui:
  title: Health Status
  header: Health Status
  logo: https://raw.githubusercontent.com/joryirving/home-ops/main/.docs/icons/lds-transparent.png
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

