# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: terraform-bitwarden-secret
stringData:
    bw_access_token: ENC[AES256_GCM,data:4J7q7em3vzRXUD9qSEgEH2SUKhpu/43eJTs+fHrW0jtQeFYdm8cDMweUzU0b4NMBKdxKlm5kyEDAGhl8IujXzmEpAH9XxTFl9WlREi6cBqW5tJhXwK4180WXET/irA==,iv:rvaA3HOtCiD1XtJ1bwrcQIJwtwBDNx9ZNqOH22S70vU=,tag:KRV6VOvwW9MQ2uKMcuwrdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12v9uw8k6myrr49z9aq6jmcwa79aepu0p6p462nrv968qcae72pcspwldec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWVR4eGJYWUJ1V0F4Z2x0
            NW8wbFQrY1YxakY3RGtuQmozbFlyL0NqekVzCmZXNWFBdVg5RlBtdUp1dHVFWDlm
            ZVlGOXRjUGpJRm1rMzh1ck5BSVhadmsKLS0tIGVqeE5HUnZVczl4NkJmNEJ1NVoz
            KzRDbWFsVEpsalByQ1pKL2VsbHZuaTQKKQ+Ia4b12/kVhKvypUlf/riQuTQFh9zy
            T/Lp0g6o1eW7KoE+tFk9QgPGYLphyXn/iVNWpz+bMTXhcgFL0qTQZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-06T17:35:52Z"
    mac: ENC[AES256_GCM,data:kqWaREkuYkNWTx33DEtMjT+Krj1MqmeU73KWN57cLTcYqNo8SmMfugqscy1TwhOOOYO7yocOb6/GnxzdPvev9pGf+7AOG5Nvl+KeUZbltG903NL0n2XxLk+RQ95hx5fH5roAlIFCNYKN37aY8XFU+WZ+SJPWnYkeWzzjsWAz640=,iv:zGl4TEf9DnJBhTp1gY+cXZr/TYGjx44ZuIC97DLztsg=,tag:V7bjt1/qWl+cx5v2Dw7D3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
