# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: terraform-secret
stringData:
    bw_access_token: ENC[AES256_GCM,data:4J7q7em3vzRXUD9qSEgEH2SUKhpu/43eJTs+fHrW0jtQeFYdm8cDMweUzU0b4NMBKdxKlm5kyEDAGhl8IujXzmEpAH9XxTFl9WlREi6cBqW5tJhXwK4180WXET/irA==,iv:rvaA3HOtCiD1XtJ1bwrcQIJwtwBDNx9ZNqOH22S70vU=,tag:KRV6VOvwW9MQ2uKMcuwrdw==,type:str]
    onepassword_sa_token: ENC[AES256_GCM,data:w6rvXcNTyWbwKU/4/o/BlkODrwCL5NQRBM01ktuVfD2HMTjd8MiK0aagvqV0bsUFTK9OEIlh4Ah1hEQj1mQFru6hblAr8D1EtP2KqQaQfmqj5d7KRBrmkkaY9AbkFTWfHH6LEs8Tu0TAPCJABC3Z5lJ6t0+kpZ5ESEaEETV1UzLmFkeLiwooBo/yHscvKjAkDUGfTb3hfyINcj9hPJb+4R65IZ2Gidg8nC8Ti0ITF+8b14rdmNJ41E7ENYtnkBTLN1XYRAAQ4SVetKc9cMkdqzqMnWABXmm8cPzR0Xspp1CCwIlTHeG8ODUJ9eOGxiLz0NuJCrXJWu8kWkU+TGxL3N+Wy2rhzEaAIwwi/q5I7z8Mxj/Fm8vE0NTm0JqaFPB+B4JUYXy0ZUyE6ziVB/lAxI1XejnBeVYJHh3opI1iNgc85j3WS2zcxaEhaLNR+TGoYWicxa0+Nja7roYuhTEKhwRYtTtlUCPqy8OKR38S+vPJG2cOiyODFLIjiIsQ5LoyMNfd4PlhKTaWKkyqnq5ZRI98tawjlcpMrkyt8POAzI6K65UcdbNdNYn7yJxy2jAXxhtZUa1kvrAzGk8D+2E4uDOw9uRXlt8f5HYrWJskF+uEkrrLIjd7JE5xSK2FYdobCxzfg+XHAQBAs2hK93ZSdt0GRMW7Ig7aKvPt+pMFF6Lqs075kikxhcquOZ20NYBd2Y2rpKNVmD4AfB7pzOVtp/Yz44iYuXx3sKql0Mwd7qEtqpsEXb+ZSpXwh9FDr0bk8j8A7b5gdhmk3KcQiY2ouIwD/g0S+dJJKKeh4IoRRXB0Vo6mpxQ5SPJ7D75swiRdrzLWx9BY15oDi3+GfxQXf0T3Padf9d/qVZzydqa+prw1ZzVwNjk/4YtWjhdDp16QB6ydxltIGeRhMJyyMKir8QyP0VgeISwXxCjnT1BFTaxeW0ONpmbxN7BagQ/8j/cm8AnisqDRtVePIdVXWF1hw/cbV+7QuZkB33ldnK9pPawCLN5aScmiEgi50rUCf0m3EW3T5z2U9oSPDcwwgjG41eF3npJa/5D5Drmumy2iImQGeslw0nsq0ttGmNMnXOLZhvo11FeWbsZtJstTxW4t0ENUlVPvyMZ4W9E1oF0nTKm53A==,iv:5R++tKZ4vHcmVzzImpq1OTHavSTx5ir0Yh2iOpptjho=,tag:jkXudrdxhQ1aOHB2J/k3xA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12v9uw8k6myrr49z9aq6jmcwa79aepu0p6p462nrv968qcae72pcspwldec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWVR4eGJYWUJ1V0F4Z2x0
            NW8wbFQrY1YxakY3RGtuQmozbFlyL0NqekVzCmZXNWFBdVg5RlBtdUp1dHVFWDlm
            ZVlGOXRjUGpJRm1rMzh1ck5BSVhadmsKLS0tIGVqeE5HUnZVczl4NkJmNEJ1NVoz
            KzRDbWFsVEpsalByQ1pKL2VsbHZuaTQKKQ+Ia4b12/kVhKvypUlf/riQuTQFh9zy
            T/Lp0g6o1eW7KoE+tFk9QgPGYLphyXn/iVNWpz+bMTXhcgFL0qTQZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-20T20:41:33Z"
    mac: ENC[AES256_GCM,data:xbvtsMX02GoC9nG5hVeOTq9dmGloF6BvkZV6KuYCroY2r4BVi7QlKfYtmPkmrkkFd+JPQ4wBscj05PvH3dxtCCYWJqvn33okyplkH9Mqdx96PtTUyFP/8o7YHIRkJY3RIy/6bZv8lUXPvtsqg/NkOpEO2l6Hvj40mQqcPnP6G98=,iv:C1+LB29XZTfa2Orku9N4fbJbO4q3iKH2KRXAW+uwzHU=,tag:jr2evHIvF9vQ63FN7IcQgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
