# yaml-language-server: $schema=https://lds-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft-vibecraft
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      version: 4.19.0
      sourceRef:
        kind: HelmRepository
        name: itzg-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
  - name: rook-ceph-cluster
    namespace: rook-ceph
  - name: volsync
    namespace: storage
  values:
    # deploymentAnnotations:
    #   secret.reloader.stakater.com/reload: minecraft-vibecraft-secret
    image:
      repository: ghcr.io/itzg/minecraft-server
      tag: stable@sha256:1ff47453ce66194927313d628c32a485c34d0acc9c01c9dbd643584c50cf89e6
    resources:
      requests:
        cpu: 500m
      limits:
        memory: 8Gi
    securityContext:
      runAsUser: &uid 568
      fsGroup: *uid
    livenessProbe:
      enabled: false
      command:
        - echo
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 20
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      enabled: false
      command:
        - echo
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 20
      successThreshold: 1
      timeoutSeconds: 1
    startupProbe:
      command:
        - echo
      enabled: false
      failureThreshold: 30
      periodSeconds: 10
    extraEnv:
      TZ: ${TIMEZONE}
      ENABLE_AUTOPAUSE: TRUE # Doesn't work in Kubes
    persistence:
      dataDir:
        enabled: true
        existingClaim: *app
      # config-file:
      #   enabled: true
      #   type: secret
      #   name: vibecraft-discord-secret
      #   globalMounts:
      #   - path: /data/plugins/DiscordSRV/config.yml
      #     subPath: config.yml
      #     readOnly: true
    serviceAnnotations:
      mc-router.itzg.me/externalServerName: vibecraft.${SECONDARY_DOMAIN}
    minecraftServer:
      eula: true
      version: 1.20.6
      type: SPIGOT
      overrideServerProperties: true
      jvmXXOpts: "-XX:MaxRAMPercentage=75"
      memory: 8192M
      difficulty: normal
      spawnProtection: 0
      gameMode: survival
      pvp: false
      onlineMode: true
      #whitelist: "LilDrunkenSmurf"
      ops: "LilDrunkenSmurf"
      motd: "Vibecraft. Come hang out and Vibe"
      worldSaveName: Vibecraft
      viewDistance: 12
      spigetResources:
      - 36618 #Prom Exporter
      - 18494 #DiscordSRV
      rcon:
        enabled: true
      extraPorts:
      - name: metrics
        containerPort: 9225
        protocol: TCP
        service:
          enabled: true
          embedded: false
          type: ClusterIP
          port: 9225
        ingress:
          enabled: false
  valuesFrom:
  - kind: Secret
    name: minecraft-vibecraft-secret
    valuesKey: RCON_PASSWORD
    targetPath: minecraftServer.rcon.password
