---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wizarr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/wizarrrr/wizarr
      tag: 3.4.1@sha256:cd2b27241002592e94223b61d7ec26871667e59efe60a242a4ea25757b9ff2d3
    env:
      TZ: ${TIMEZONE}
      APP_URL: https://join.${SECRET_DOMAIN}
      DISABLE_BUILTIN_AUTH: "false"
    service:
      main:
        ports:
          http:
            port: 5690
    ingress:
      main:
        enabled: true
        ingressClassName: external
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: wizarr.png
          gethomepage.dev/name: Wizarr
          gethomepage.dev/group: Media
          # gethomepage.dev/widget.type: wizarr
          # gethomepage.dev/widget.url: http://wizarr.media.svc.cluster.local:5690
          # gethomepage.dev/widget.key: ${WIZARR_TOKEN}
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "join.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    volumeClaimTemplates:
      - name: config
        mountPath: /data/database
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn-config
    resources:
      requests:
        cpu: 15m
        memory: 180M
      limits:
        memory: 300M
