---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-tools
resources:
  - ./fstrim/ks.yaml
  - ./node-feature-discovery/ks.yaml
  # - ./powertune/ks.yaml
  - ./reloader/ks.yaml
  - ./system-upgrade-controller/ks.yaml
components:
  - ../../../shared/components/alerts
  - ../../../shared/components/namespace
patches:
  - patch: |
      - op: add
        path: /metadata/name
        value: kube-tools
    target:
      kind: Namespace
