---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name thanos-objstore-config
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        config: |-
          type: s3
          config:
            bucket: thanos
            endpoint: rgw.${PRIMARY_DOMAIN}
            access_key: {{ .AWS_ACCESS_KEY_ID }}
            secret_key: {{ .AWS_SECRET_ACCESS_KEY }}
  dataFrom:
    - extract:
        key: thanos
