---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: wireguard
spec:
  endpoints:
    - dnsName: vpn.${SECRET_DOMAIN}
      recordType: CNAME
      targets: ["ipv4.${SECRET_DOMAIN}"] # DDNS
