apiVersion: 1
kind: Secret
metadata:
    name: bws-secret
stringData:
    token: ENC[AES256_GCM,data:cgZoXvRDeANUDAv9y5AgcYdIod+lRTI6Gqpi0BO8x1qq9+Wg8EQPenTjCwekSMu9mm8MOn59AKavH2SuoQwi+UBBeLlTyyEJ+bYFH9uorkaO4kl0nfjfjj2PICHPuQ==,iv:OUvqDld+aq+Tp48uGt68/s+saEGf0hDoNlKTsQCAiN4=,tag:FecIjgOdeSp5Tbb+iPKb4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12v9uw8k6myrr49z9aq6jmcwa79aepu0p6p462nrv968qcae72pcspwldec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWVR4eGJYWUJ1V0F4Z2x0
            NW8wbFQrY1YxakY3RGtuQmozbFlyL0NqekVzCmZXNWFBdVg5RlBtdUp1dHVFWDlm
            ZVlGOXRjUGpJRm1rMzh1ck5BSVhadmsKLS0tIGVqeE5HUnZVczl4NkJmNEJ1NVoz
            KzRDbWFsVEpsalByQ1pKL2VsbHZuaTQKKQ+Ia4b12/kVhKvypUlf/riQuTQFh9zy
            T/Lp0g6o1eW7KoE+tFk9QgPGYLphyXn/iVNWpz+bMTXhcgFL0qTQZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-08T17:02:32Z"
    mac: ENC[AES256_GCM,data:XS/i9nPqBnhtW9OAn0i/8N/cVtnYlN6trNFkjzy1FRuwYuADaVHgLWJlj1Vp2YiMwGlINurUVtyRFUDpeJe6Nt6bohWG7Fl7CtjGm6oCFNYocl6+++wbTPm2OY7oMAWsRGkp79JmQmQws/RdYgNuip7RkA78aTNcDTvlpHP6tks=,iv:htb6b5NQRzv885rlz0j76Obmefp20075zYgMAHMmfAk=,tag:EZ/4U30hiToOP3F5pHOQSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: bws-secret-org
stringData:
    ORG_ID: ENC[AES256_GCM,data:LxGlNDbW7lwP3JdeOBaBHZR7YXaIZJ8NRPYqhYJLOYDZXZNU,iv:OtJyTdqscLtZd67+C5ktyL3AZTp+ZYHZZ54sDJwJD8k=,tag:1tI3pA23w7vHci+VT/vL6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12v9uw8k6myrr49z9aq6jmcwa79aepu0p6p462nrv968qcae72pcspwldec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWVR4eGJYWUJ1V0F4Z2x0
            NW8wbFQrY1YxakY3RGtuQmozbFlyL0NqekVzCmZXNWFBdVg5RlBtdUp1dHVFWDlm
            ZVlGOXRjUGpJRm1rMzh1ck5BSVhadmsKLS0tIGVqeE5HUnZVczl4NkJmNEJ1NVoz
            KzRDbWFsVEpsalByQ1pKL2VsbHZuaTQKKQ+Ia4b12/kVhKvypUlf/riQuTQFh9zy
            T/Lp0g6o1eW7KoE+tFk9QgPGYLphyXn/iVNWpz+bMTXhcgFL0qTQZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-08T17:02:32Z"
    mac: ENC[AES256_GCM,data:XS/i9nPqBnhtW9OAn0i/8N/cVtnYlN6trNFkjzy1FRuwYuADaVHgLWJlj1Vp2YiMwGlINurUVtyRFUDpeJe6Nt6bohWG7Fl7CtjGm6oCFNYocl6+++wbTPm2OY7oMAWsRGkp79JmQmQws/RdYgNuip7RkA78aTNcDTvlpHP6tks=,iv:htb6b5NQRzv885rlz0j76Obmefp20075zYgMAHMmfAk=,tag:EZ/4U30hiToOP3F5pHOQSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
