---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - ./home-assistant/ks.yaml
  - ./mosquitto/ks.yaml
  - ./rtlamr2mqtt/ks.yaml
  - ./zigbee2mqtt/ks.yaml
components:
  - ../../../shared/components/alerts
  - ../../../shared/components/namespace
patches:
  - # Add the name to the namespace
    patch: |
      - op: add
        path: /metadata/name
        value: home-automation
    target:
      kind: Namespace
