---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: vm-additional-scrape-configs
stringData:
  prometheus-additional.yaml: |
    - job_name: blocky
      scrape_interval: 1m
      scrape_timeout: 10s
      honor_timestamps: true
      static_configs:
        - targets:
            - blocky.${SECRET_DOMAIN}

    - job_name: node-exporter
      scrape_timeout: 10s
      honor_timestamps: true
      static_configs:
        - targets:
          - voyager.internal:9100
          - pikvm.internal:9100

    - job_name: smartctl-exporter
      scrape_interval: 10m
      scrape_timeout: 10s
      honor_timestamps: true
      static_configs:
        - targets:
            - voyager.internal:9633

    - job_name: pikvm
      scrape_interval: 10m
      scrape_timeout: 10s
      honor_timestamps: true
      metrics_path: /api/export/prometheus/metrics
      static_configs:
        - targets:
            - pikvm.internal

    - job_name: minio-job
      scrape_interval: 10m
      scrape_timeout: 10s
      honor_timestamps: true
      metrics_path: /minio/v2/metrics/cluster
      static_configs:
        - targets:
            - s3.${SECRET_DOMAIN}
