---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2023.10.7
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  values:
    strategy:
      type: RollingUpdate
    worker:
      strategy:
        type: RollingUpdate
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-init:16
        imagePullPolicy: IfNotPresent
        envFrom: &envFrom
          - secretRef:
              name: authentik-secret
    ingress:
      enabled: true
      ingressClassName: external
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/icon: authentik.png
        gethomepage.dev/name: Authentik
        gethomepage.dev/group: Infrastructure
        gethomepage.dev/widget.type: authentik
        gethomepage.dev/widget.url: https://authentik.${SECRET_DOMAIN}
        gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_AUTHENTIK_TOKEN}}"
        external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
      hosts:
        - host: &host authentik.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
          secretName: *host
    podAnnotations:
      secret.reloader.stakater.com/reload: authentik-secrets
    authentik:
      redis:
        host: dragonfly.database.svc.cluster.local
    env:
      AUTHENTIK_REDIS__DB: "1"
    envFrom: *envFrom
    autoscaling:
      server:
        enabled: true
        minReplicas: 2
      worker:
        enabled: true
        minReplicas: 2
    prometheus:
      serviceMonitor:
        create: true
      rules:
        create: true
