---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: powertune
  namespace: kube-tools
  labels:
    app.kubernetes.io/name: powertune
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: powertune
  template:
    metadata:
      labels:
        app.kubernetes.io/name: powertune
    spec:
      containers:
      - image: ghcr.io/runningman84/powertune:main@sha256:9d09e9d16eae3d81a57e12a0af1cb6fd343f0dca13977803dfaea19dd054e953
        imagePullPolicy: IfNotPresent
        name: powertune
        command: ["/bin/sh", "-c", "sleep 86400"]
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host
          name: hostfs
      dnsPolicy: ClusterFirstWithHostNet
      hostIPC: true
      hostNetwork: true
      hostPID: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /
          type: ""
        name: hostfs
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
