---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name kyoo-chart-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # App
        kyoo_apikeys: '{{ .KYOO_API_KEY }}'
        TMDB_API_KEY: '{{ .TMDB_API_KEY }}'
        TVDB_APIKEY: ""
        TVDB_PIN: ""
        #Meili
        MEILI_MASTER_KEY: '{{ .MEILI_MASTER_KEY }}'
        #RabbitMQ
        RABBITMQ_USER: kyoo
        RABBITMQ_COOKIE: '{{ .RABBITMQ_COOKIE }}'
        RABBITMQ_PASS: '{{ .RABBITMQ_PASS }}'
        # OIDC
        OIDC_AUTHENTIK_NAME: Authentik
        OIDC_AUTHENTIK_LOGO: https://sso.${SECRET_DOMAIN}/static/dist/assets/icons/icon.png
        OIDC_AUTHENTIK_AUTHORIZATION: https://sso.${SECRET_DOMAIN}/application/o/authorize/
        OIDC_AUTHENTIK_TOKEN: https://sso.${SECRET_DOMAIN}/application/o/token/
        OIDC_AUTHENTIK_PROFILE: https://sso.${SECRET_DOMAIN}/application/o/userinfo/
        OIDC_AUTHENTIK_SCOPE: openid email profile
        clientId: '{{ .KYOO_CLIENT_ID }}'
        clientSecret: '{{ .KYOO_CLIENT_SECRET }}'
        # Postgres
        POSTGRES_USER: kyoo_all #temp
        POSTGRES_PASSWORD: watchSomething4me #temp
  dataFrom:
  - extract:
      key: kyoo
  - extract:
      key: kometa
