---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kyoo-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        AUTHENTICATION_SECRET: '{{ .KYOO_AUTH_SECRET }}'
        KYOO_APIKEYS: '{{ .KYOO_API_KEY }}'
        MEILI_MASTER_KEY: '{{ .MEILI_MASTER_KEY }}'
        RABBITMQ_DEFAULT_PASS: '{{ .RABBITMQ_PASS }}'
        THEMOVIEDB_APIKEY: '{{ .TMDB_API_KEY }}'
        # OIDC
        OIDC_AUTHENTIK_CLIENTID: '{{ .KYOO_CLIENT_ID }}'
        OIDC_AUTHENTIK_SECRET: '{{ .KYOO_CLIENT_SECRET }}'
  dataFrom:
  - extract:
      key: kyoo
  - extract:
      key: plex-meta-manager
---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name kyoo-db-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: kyoo-secret
    creationPolicy: Merge
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        POSTGRES_DB: '{{ .dbname }}'
        POSTGRES_SERVER: '{{ index . "pgbouncer-uri" }}'
        POSTGRES_PORT: '{{ .port }}'
        POSTGRES_USER: '{{ .user }}'
        POSTGRES_PASSWORD: '{{ .password }}'
  dataFrom:
  - extract:
      key: postgres-pguser-kyoo
