---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name kyoo-secret
spec:
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # App
        KYOO_API_KEY: '{{ .KYOO_API_KEY }}'
        TMDB_API_KEY: '{{ .TMDB_API_KEY }}'
        TVDB_APIKEY: ""
        TVDB_PIN: ""
        #Meili
        MEILI_MASTER_KEY: '{{ .MEILI_MASTER_KEY }}'
        #RabbitMQ
        RABBITMQ_USER: kyoo
        RABBITMQ_COOKIE: '{{ .RABBITMQ_COOKIE }}'
        RABBITMQ_PASS: '{{ .RABBITMQ_PASS }}'
        # OIDC
        OIDC_AUTHENTIK_NAME: Authentik
        OIDC_AUTHENTIK_LOGO: https://sso.${SECRET_DOMAIN}/static/dist/assets/icons/icon.png
        OIDC_AUTHENTIK_AUTHORIZATION: https://sso.${SECRET_DOMAIN}/application/o/authorize/
        OIDC_AUTHENTIK_TOKEN: https://sso.${SECRET_DOMAIN}/application/o/token/
        OIDC_AUTHENTIK_PROFILE: https://sso.${SECRET_DOMAIN}/application/o/userinfo/
        OIDC_AUTHENTIK_SCOPE: openid email profile
        OIDC_AUTHENTIK_CLIENTID: '{{ .KYOO_CLIENT_ID }}'
        OIDC_AUTHENTIK_SECRET: '{{ .KYOO_CLIENT_SECRET }}'
        # Database
        POSTGRES_DB: '{{ .dbname }}'
        POSTGRES_SERVER: '{{ .host }}'
        POSTGRES_PORT: '{{ .port }}'
        POSTGRES_USER: '{{ .user }}'
        POSTGRES_PASSWORD: '{{ .password }}'
  dataFrom:
  - extract:
      key: kyoo
    sourceRef: &onepass
       storeRef:
         kind: ClusterSecretStore
         name: onepassword-connect
  - extract:
      key: kometa
    sourceRef: *onepass
  - extract:
      key: postgres-pguser-kyoo
    sourceRef:
       storeRef:
         kind: ClusterSecretStore
         name: crunchy-pgo-secrets
