---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kyoo-chart
spec:
  interval: 15m
  chart:
    spec:
      chart: ./chart
      sourceRef:
        kind: GitRepository
        name: kyoo
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      strategy: rollback
      retries: 3
  values:
    meilisearch:
      enabled: true
      infra:
        # DOES NOT SUPPORT SPECIFYING KEY.  MUST BE NAMED `MEILI_MASTER_KEY`
        existingSecret: &secret kyoo-chart-secret
      kyoo_back:
        masterkeyKey: MEILI_MASTER_KEY
        existingSecret: *secret
    postgres:
      enabled: true
      #infra is only used by subchart deployment
      infra:
        # subchart does not accept this global value in one place
        # if updating be sure to also update postgresql.auth.username
        user: kyoo_all
        passwordKey: POSTGRES_PASSWORD
        existingSecret: *secret
      kyoo_back:
        host: kyoo-postgresql
        port: 5432
        database: kyoo_back
        kyoo_migrations:
          userKey: POSTGRES_USER
          passwordKey: POSTGRES_PASSWORD
          existingSecret: *secret
        kyoo_back:
          userKey: POSTGRES_USER
          passwordKey: POSTGRES_PASSWORD
          existingSecret: *secret
      kyoo_transcoder:
        host: kyoo-postgresql
        port: 5432
        database: kyoo_transcoder
        # POSTGRES_SCHEMA disabled means application will not create the schema
        # and will instead use the user's search path
        schema: disabled
        kyoo_transcoder:
          userKey: POSTGRES_USER
          passwordKey: POSTGRES_PASSWORD
          existingSecret: *secret
    rabbitmq:
      enabled: true
      host: kyoo-rabbitmq
      port: 5672
      #infra is only used by subchart deployment
      infra:
        passwordKey: RABBITMQ_PASS
        keyErlangCookie: RABBITMQ_COOKIE
        existingSecret: *secret
      kyoo_autosync:
        userKey: RABBITMQ_USER
        passwordKey: RABBITMQ_PASS
        existingSecret: *secret
      kyoo_back:
        userKey: RABBITMQ_USER
        passwordKey: RABBITMQ_PASS
        existingSecret: *secret
      kyoo_matcher:
        userKey: RABBITMQ_USER
        passwordKey: RABBITMQ_PASS
        existingSecret: *secret
      kyoo_scanner:
        userKey: RABBITMQ_USER
        passwordKey: RABBITMQ_PASS
        existingSecret: *secret

    kyoo:
      address: https://kyoo-chart.${SECRET_DOMAIN}
      requireAccountVerification: true
      defaultPermissions: "overall.read,overall.play"
      unloggedPermissions: ""
      libraryIgnorePattern: ""
      languages: "en"
      # hardware acceleration profile (valid values: disabled, vaapi, qsv, nvidia)
      transcoderAcceleration: vaapi
      # the preset used during transcode. faster means worst quality, you can probably use a slower preset with hwaccels
      # warning: using vaapi hwaccel disable presets (they are not supported).
      transcoderPreset: fast
      apikey:
        existingSecret: *secret
        apikeyKey: kyoo_apikeys
      oidc:
        enabled: false
        existingSecret: *secret
        authMethod: ClientSecretBasic

    contentdatabase:
      # TheMovieDB
      tmdb:
        apikeyKey: TMDB_API_KEY
        existingSecret: *secret
      # TVDatabase
      tvdb:
        apikeyKey: TVDB_APIKEY
        pinKey: TVDB_PIN
        existingSecret: *secret

    ingress:
      enabled: true
      ingressClassName: external
      annotations:
        external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
      host: kyoo-chart.${SECRET_DOMAIN}
      tls: true
