apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:olHOkyyRYoJsPRX3Rw==,iv:odKhYForOw05FJ2gxuleIpXFEDLBCiFpI5F5QZjZIvk=,tag:ypV4xi3YGbKjGu+sezpmHQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:T1MjNF1zdwsI1LpTkKsJADovUXCsHoKTI3sYcvoJOy01ZmpY,iv:utn/W/euk6A3GdPEaLaH4sWw7qKydHgnuIXkIk2CcMs=,tag:xyad2JjnpzNzyPTAIwvRrA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:kJHm5FKkZPk=,iv:MBokZ0nTIZa/oj5q9HhmET+8Ha0afk9+n15KSBwhfjs=,tag:N21wpFFWJrBC8p/Dk6SVdg==,type:str]
    CLUSTER_NAME: ENC[AES256_GCM,data:BpA=,iv:HR3bNMxxq31vfOrL8Mcupygmar9SHrmWOznmLqRrlv0=,tag:rolEqE3XKxns3CF140dLbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12v9uw8k6myrr49z9aq6jmcwa79aepu0p6p462nrv968qcae72pcspwldec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SnlFNVh6cDhuaXdSdXg1
            a2IwUXFvejRQc2Z6NlR4ak5pdWJ5Q1JtU3pjCldleml5RXA4Tk5wc3VQZW5kNXlm
            enpieDhJL3dUQkxKQ2hKVldiTFhGa2MKLS0tIFV2ZWFJTGVodmNhS0FUQzZMbExY
            ZjkzSGxlT1R6VHNHNDVNb3hBVzNVZ3MKMtBhVS0FKr6NWqv9S6mSOhjCDIdO3uNz
            OS9Qh8tX5J/s1ZH6z3/DNLWKonA6mccm1kH7jNQe/+w4ozYxa4me9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-19T15:47:34Z"
    mac: ENC[AES256_GCM,data:Ksv16+pgMzlWkhSX3OcDCysAUqfKFqzeuV4tfj1B8jouyG5uaJjJYCBu11VTOzB3JV5X2xG97Rplaw3JRzswCIPGLkIKsjlmlrVq0qbsWpbmnjbL1DGjpfIi6pz6Y/TqWEhRd47ILHhyrO0WOyvGyTNfcSXcDSbjnl8oKyEWMkQ=,iv:6qyBBCmQkHTz5AV4FhtlugCO1zyYuWgi7eeULiTa7aU=,tag:ArEScH6jNc7ejQKXmL6rEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
