apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:olHOkyyRYoJsPRX3Rw==,iv:odKhYForOw05FJ2gxuleIpXFEDLBCiFpI5F5QZjZIvk=,tag:ypV4xi3YGbKjGu+sezpmHQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:T1MjNF1zdwsI1LpTkKsJADovUXCsHoKTI3sYcvoJOy01ZmpY,iv:utn/W/euk6A3GdPEaLaH4sWw7qKydHgnuIXkIk2CcMs=,tag:xyad2JjnpzNzyPTAIwvRrA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:ycxHaXX9nqf+8QxJSByyVpXuxA==,iv:Iek3gzaLdDUHOp1mPWQ+XOi0DJZJfS6l3DkWUJnHavY=,tag:kCAxFx46/Ea1TFu/5hOapw==,type:str]
    CLUSTER_NAME: ENC[AES256_GCM,data:KvFGzA==,iv:paighFPW7ZY0GVtEa0uiz+9SdZJGRBg2EEwGCYHtzu4=,tag:YSWvML9UJiTMPBCVqL9R2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12v9uw8k6myrr49z9aq6jmcwa79aepu0p6p462nrv968qcae72pcspwldec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SnlFNVh6cDhuaXdSdXg1
            a2IwUXFvejRQc2Z6NlR4ak5pdWJ5Q1JtU3pjCldleml5RXA4Tk5wc3VQZW5kNXlm
            enpieDhJL3dUQkxKQ2hKVldiTFhGa2MKLS0tIFV2ZWFJTGVodmNhS0FUQzZMbExY
            ZjkzSGxlT1R6VHNHNDVNb3hBVzNVZ3MKMtBhVS0FKr6NWqv9S6mSOhjCDIdO3uNz
            OS9Qh8tX5J/s1ZH6z3/DNLWKonA6mccm1kH7jNQe/+w4ozYxa4me9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-18T20:48:46Z"
    mac: ENC[AES256_GCM,data:4c0Z01QweIuF2eItIWTCTKzSCIEi3O8HE9mt7A6qRqB42Zie4CGqBhkgX5vB+nRDSxoDVTgjcmYWs9bGcFGbDdcxyMtKoVTRuqeI28CL8etx8G2GxxkCbT8FApTEXRZgAjltbtcAxD9BYr9wnKb9/u4pokk+66U/hTYuK1WIHB0=,iv:l5w7IuHpG2YYZIGP0Aw5APnYIwYBQte3gxFoZWyHl8o=,tag:l8HLi90iIxYvWxlLWwpOhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
