---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.7.2
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    csi:
      attacherReplicaCount: &replicas 2
      provisionerReplicaCount: *replicas
      resizerReplicaCount: *replicas
      snapshotterReplicaCount: *replicas
    persistence:
      defaultClassReplicaCount: 2
    defaultSettings:
      createDefaultDiskLabeledNodes: true
      defaultDataLocality: true
      replicaAutoBalance: true
      storageMinimalAvailablePercentage: 1
      storageReservedPercentageForDefaultDisk: 1 # Dedicated disk
      defaultLonghornStaticStorageClass: longhorn
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      concurrentAutomaticEngineUpgradePerNodeLimit: 3
      orphanAutoDeletion: true
    longhornUI:
      replicas: *replicas
    ingress:
      enabled: true
      ingressClassName: internal
      host: longhorn.${SECRET_DOMAIN}
      tls: true
    metrics:
      serviceMonitor:
        enabled: true
