---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name grafana-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # Authentik
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ .GRAFANA_CLIENT_ID }}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .GRAFANA_CLIENT_SECRET }}"
        # Admin User
        adminUser: "{{ .GRAFANA_ADMIN_USER }}"
        adminPass: "{{ .GRAFANA_ADMIN_PASS }}"
        # App
        GF_DATABASE_USER: &dbUser "{{ .POSTGRES_USER }}"
        GF_DATABASE_PASSWORD: &dbPass "{{ .POSTGRES_PASS }}"
        GF_DATABASE_HOST: &dbHost postgres-rw.database.svc.cluster.local
        GF_DATABASE_NAME: &dbname grafana
        GF_DATABASE_SSL_MODE: disable
        GF_DATABASE_TYPE: postgres
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
  - extract:
      key: grafana
  - extract:
      key: cloudnative-pg
