---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: home-kubernetes
  namespace: flux-system
spec:
  interval: 30m
  url: "https://github.com/joryirving/home-ops.git"
  ref:
    branch: "main"
  ignore: |
    # exclude all
    /*
    # include kubernetes directory
    !/kubernetes/utility
    !/kubernetes/shared
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-shared
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/shared
  prune: false # revert to true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - name: cluster-settings
        kind: ConfigMap
        optional: true
      - name: cluster-secrets
        kind: Secret
        optional: true
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 30m
  dependsOn:
    - name: cluster-shared
  path: ./kubernetes/utility/flux
  prune: false # revert to true
  wait: false
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - name: cluster-settings
        kind: ConfigMap
        optional: true
      - name: cluster-settings-utility
        kind: ConfigMap
        optional: true
      - name: cluster-secrets
        kind: Secret
        optional: true
      - name: cluster-secrets-utility
        kind: Secret
        optional: true
