---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./ersatztv/ks.yaml
  - ./kavita/ks.yaml
  - ./komga/ks.yaml
  # - ./kyoo/ks.yaml
  - ./maintainerr/ks.yaml
  - ./overseerr/ks.yaml
  - ./plex/ks.yaml
  - ./tautulli/ks.yaml
  - ./wizarr/ks.yaml
  - ./your-spotify/ks.yaml
