---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./ersatztv/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./kavita/ks.yaml
  - ./komga/ks.yaml
  - ./kyoo/ks.yaml
  - ./maintainerr/ks.yaml
  - ./plex/ks.yaml
  - ./tautulli/ks.yaml
  - ./wizarr/ks.yaml
  - ./your-spotify/ks.yaml
components:
  - ../../../shared/components/alerts
  - ../../../shared/components/namespace
patches:
  - # Add the name to the namespace
    patch: |
      - op: add
        path: /metadata/name
        value: media
    target:
      kind: Namespace
