# yaml-language-server: $schema=https://lds-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app minecraft-create
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      version: 4.15.0
      sourceRef:
        kind: HelmRepository
        name: itzg-charts
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
  - name: rook-ceph-cluster
    namespace: rook-ceph
  - name: volsync
    namespace: storage
  values:
    deploymentAnnotations:
      secret.reloader.stakater.com/reload: minecraft-create-secret
    image:
      repository: ghcr.io/itzg/minecraft-server
      tag: java17
    resources:
      requests:
        cpu: 500m
      limits:
        memory: 8Gi
    securityContext:
      runAsUser: &uid 568
      fsGroup: *uid
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false
    extraEnv:
      TZ: ${TIMEZONE}
      ENABLE_AUTOPAUSE: FALSE # Doesn't work in Kubes
    persistence:
      dataDir:
        enabled: true
        existingClaim: *app
    serviceAnnotations:
      mc-router.itzg.me/externalServerName: "create.${SECONDARY_DOMAIN}" ## Manual DNS management
    minecraftServer:
      eula: true
      version: 1.20.1
      type: FORGE
      forceReDownload: true
      jvmXXOpts: "-XX:MaxRAMPercentage=75"
      memory: 8192M
      difficulty: normal
      spawnProtection: 0
      maxTickTime: -1
      gameMode: survival
      pvp: false
      onlineMode: false
      #whitelist: "LilDrunkenSmurf"
      ops: "LilDrunkenSmurf"
      motd: "Create Server test"
      worldSaveName: create
      viewDistance: 12
      modUrls:
      - "https://edge.forgecdn.net/files/4835/191/create-1.20.1-0.5.1.f.jar?api-key=267C6CA3"
      # spigetResources:
      # - 36618 #Prom Exporter
      # - 18494 #DiscordSRV
      rcon:
        enabled: true
        serviceType: ClusterIP
      serviceType: ClusterIP
      extraPorts:
      - name: metrics
        containerPort: 9225
        protocol: TCP
        service:
          enabled: true
          embedded: false
          type: ClusterIP
          port: 9225
        ingress:
          enabled: false
      - name: map
        containerPort: 8123
        protocol: TCP
        service:
          enabled: true
          embedded: false
          type: ClusterIP
          port: 8123
        ingress:
          enabled: true
          ingressClassName: internal
          annotations:
            gethomepage.dev/enabled: "true"
            gethomepage.dev/icon: minecraft.png
            gethomepage.dev/name: Create
            gethomepage.dev/group: Games
            gethomepage.dev/description: Create Server
            gethomepage.dev/widget.type: minecraft
            gethomepage.dev/widget.url: udp://minecraft-create-minecraft.games:25565
          hosts:
          - name: &host "create.${SECRET_DOMAIN}"
            path: /
          tls:
          - secretName: *host
            hosts:
            - *host
  valuesFrom:
  - kind: Secret
    name: minecraft-create-secret
    valuesKey: RCON_PASSWORD
    targetPath: minecraftServer.rcon.password
