---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudnative-pg-backup
  namespace: database
spec:
  schedule: "0 17 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          automountServiceAccountToken: false
          enableServiceLinks: false
          securityContext:
            runAsUser: 1031
            runAsGroup: 1031
            fsGroup: 1031
            supplementalGroups:
              - 65541
          containers:
            - name: postgres-backup
              image: docker.io/prodrigestivill/postgres-backup-local:15@sha256:7f12039af361b71c987ad06b5c0a9dca67bad92f10bffa5012a614311363eebb
              imagePullPolicy: IfNotPresent
              command:
                - "/backup.sh"
              env:
                - name: POSTGRES_HOST
                  value: postgres-ro.database.svc.cluster.local
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: cloudnative-pg-secret
                      key: username
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: cloudnative-pg-secret
                      key: password
                - name: POSTGRES_DB
                  value: "authentik,bazarr,gatus,grafana,paperless,prowlarr_log,prowlarr_main,radarr_log,radarr_main,readarr_cache,readarr_log,readarr_main"
              volumeMounts:
                - name: nas-backups
                  mountPath: /backups
          restartPolicy: OnFailure
          volumes:
            - name: nas-backups
              nfs:
                server: ${NAS_IP}
                path: ${SECRET_NFS_POSTGRES}
