---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: bitwarden
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/ripplefcl/bws-cache
              tag: latest@sha256:9f60a8e009300263a773053f8f04aac8f2f66f3bb7416f4a0a8a5ad5d7376a26
            envFrom:
              - secretRef:
                  name: bws-secret-org
            # probes:
            #   liveness:
            #     enabled: true
            #     custom: true
            #     spec:
            #       exec:
            #         command:  ["wget", "-q", "http://127.0.0.1:8087/sync", "--post-data=''"]
            #       timeoutSeconds: 5
            #   readiness:
            #     enabled: false
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 512Mi
    service:
      main:
        ports:
          http:
            port: 5000
