apiVersion: 1
kind: Secret
metadata:
    name: bws-secret
stringData:
    token: ENC[AES256_GCM,data:9AXAazCSNGwrqsjVvrEW8nX5cE7uCAthlYOv2rEA36PZNKA0GGzJolmIlrjgNOP81SG1ixTnJP9pCK8=,iv:aXtQHI2nss/l203ADn88xjiUkiTiz1EC91Ye3vq1fPQ=,tag:hXgiaGQzGyAfFTP1RRiIDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12v9uw8k6myrr49z9aq6jmcwa79aepu0p6p462nrv968qcae72pcspwldec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWVR4eGJYWUJ1V0F4Z2x0
            NW8wbFQrY1YxakY3RGtuQmozbFlyL0NqekVzCmZXNWFBdVg5RlBtdUp1dHVFWDlm
            ZVlGOXRjUGpJRm1rMzh1ck5BSVhadmsKLS0tIGVqeE5HUnZVczl4NkJmNEJ1NVoz
            KzRDbWFsVEpsalByQ1pKL2VsbHZuaTQKKQ+Ia4b12/kVhKvypUlf/riQuTQFh9zy
            T/Lp0g6o1eW7KoE+tFk9QgPGYLphyXn/iVNWpz+bMTXhcgFL0qTQZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-08T16:57:05Z"
    mac: ENC[AES256_GCM,data:oFM+StCr/TfHjB/NmaWBgI7JoMIsuAK0y82gp1wZwxvmuCklRyG6dAEZcB3I9536suWLhl1jlrIAW8IjQgnJbDLKwyF4+CdhQHTRjpV+jL8O5xccY+6qHjJ/YfcaqlcKkqYfjmkHG3kNb/xfRyqlJUENoUuziskG5+AaqU3UjkU=,iv:x6V9kbqTQiFtCLOkdduqZw708QMwaLqvSuQlraVZU9c=,tag:MSHxizprjhFDso2OBH13NA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: bws-secret-org
stringData:
    ORG_ID: ENC[AES256_GCM,data:LxGlNDbW7lwP3JdeOBaBHZR7YXaIZJ8NRPYqhYJLOYDZXZNU,iv:OtJyTdqscLtZd67+C5ktyL3AZTp+ZYHZZ54sDJwJD8k=,tag:1tI3pA23w7vHci+VT/vL6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12v9uw8k6myrr49z9aq6jmcwa79aepu0p6p462nrv968qcae72pcspwldec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWVR4eGJYWUJ1V0F4Z2x0
            NW8wbFQrY1YxakY3RGtuQmozbFlyL0NqekVzCmZXNWFBdVg5RlBtdUp1dHVFWDlm
            ZVlGOXRjUGpJRm1rMzh1ck5BSVhadmsKLS0tIGVqeE5HUnZVczl4NkJmNEJ1NVoz
            KzRDbWFsVEpsalByQ1pKL2VsbHZuaTQKKQ+Ia4b12/kVhKvypUlf/riQuTQFh9zy
            T/Lp0g6o1eW7KoE+tFk9QgPGYLphyXn/iVNWpz+bMTXhcgFL0qTQZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-08T16:57:05Z"
    mac: ENC[AES256_GCM,data:oFM+StCr/TfHjB/NmaWBgI7JoMIsuAK0y82gp1wZwxvmuCklRyG6dAEZcB3I9536suWLhl1jlrIAW8IjQgnJbDLKwyF4+CdhQHTRjpV+jL8O5xccY+6qHjJ/YfcaqlcKkqYfjmkHG3kNb/xfRyqlJUENoUuziskG5+AaqU3UjkU=,iv:x6V9kbqTQiFtCLOkdduqZw708QMwaLqvSuQlraVZU9c=,tag:MSHxizprjhFDso2OBH13NA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
