---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
resources:
  - ./bazarr/ks.yaml
  - ./dashbrr/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./kapowarr/ks.yaml
  - ./metube/ks.yaml
  - ./mylar/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./readarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
components:
  - ../../../shared/components/alerts
  - ../../../shared/components/namespace
patches:
  - patch: |
      - op: add
        path: /metadata/name
        value: downloads
    target:
      kind: Namespace
