# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.8.4
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.31.4

clusterName: &cluster utility
endpoint: https://10.69.1.120:6443
clusterPodNets:
  - "10.42.0.0/16"
clusterSvcNets:
  - "10.43.0.0/16"
additionalApiServerCertSans: &sans
  - "10.69.1.120"
  - 127.0.0.1 # KubePrism
additionalMachineCertSans: *sans
cniConfig:
  name: none

nodes:
  - hostname: "celestia"
    ipAddress: "10.69.1.121"
    installDisk: /dev/sda
    talosImageURL: factory.talos.dev/installer/2dcd442954d67662d41c61bdb92165aaf7189aff9997bd011b6968c12ce8d9c0
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: 84:47:09:2d:52:52
        dhcp: true
        mtu: 1500
        vip:
          ip: "10.69.1.120"

patches:
  # Configure containerd
  - |
    machine:
      files:
        - op: create
          path: /etc/cri/conf.d/20-customization.part
          content: |
            [plugins."io.containerd.grpc.v1.cri"]
              enable_unprivileged_ports = true
              enable_unprivileged_icmp = true
            [plugins."io.containerd.grpc.v1.cri".containerd]
              discard_unpacked_layers = false
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
              discard_unpacked_layers = false

  # Configure NFS Mounts
  - |
    machine:
      files:
        - op: overwrite
          path: /etc/nfsmount.conf
          permissions: 0o644
          content: |
            [ NFSMount_Global_Options ]
            nfsvers=4.2
            hard=True
            nconnect=16
            noatime=True

  # Disable search domain everywhere
  - |-
    machine:
      network:
        disableSearchDomain: true

  # Enable cluster discovery
  - |-
    cluster:
      discovery:
        registries:
          kubernetes:
            disabled: false
          service:
            disabled: true

  # Configure kubelet
  - |-
    machine:
      kubelet:
        extraArgs:
          image-gc-low-threshold: 50
          image-gc-high-threshold: 55
          rotate-server-certificates: true
        nodeIP:
          validSubnets:
            - "10.69.1.0/24"

  # Custom sysctl settings
  - |-
    machine:
      sysctls:
        fs.inotify.max_user_watches: 1048576
        fs.inotify.max_user_instances: 8192
        net.core.netdev_max_backlog: 30000
        net.core.rmem_max: 67108864
        net.core.wmem_max: 67108864
        net.ipv4.tcp_rmem: 4096 87380 33554432
        net.ipv4.tcp_wmem: 4096 65536 33554432
        net.ipv4.tcp_tw_reuse: 1
        net.ipv4.tcp_window_scaling: 1

  # Custom sysfs settings
  - |-
    machine:
      sysfs:
        devices.system.cpu.cpu0.cpufreq.energy_performance_preference: balance_power
        devices.system.cpu.cpu1.cpufreq.energy_performance_preference: balance_power
        devices.system.cpu.cpu2.cpufreq.energy_performance_preference: balance_power
        devices.system.cpu.cpu3.cpufreq.energy_performance_preference: balance_power
        devices.system.cpu.cpu4.cpufreq.energy_performance_preference: balance_power
        devices.system.cpu.cpu5.cpufreq.energy_performance_preference: balance_power
        devices.system.cpu.cpu6.cpufreq.energy_performance_preference: balance_power
        devices.system.cpu.cpu7.cpufreq.energy_performance_preference: balance_power
        devices.system.cpu.cpu8.cpufreq.energy_performance_preference: balance_power
        devices.system.cpu.cpu9.cpufreq.energy_performance_preference: balance_power
        devices.system.cpu.cpu10.cpufreq.energy_performance_preference: balance_power
        devices.system.cpu.cpu11.cpufreq.energy_performance_preference: balance_power
        devices.system.cpu.cpu12.cpufreq.energy_performance_preference: balance_power
        devices.system.cpu.cpu13.cpufreq.energy_performance_preference: balance_power
        devices.system.cpu.cpu14.cpufreq.energy_performance_preference: balance_power
        devices.system.cpu.cpu15.cpufreq.energy_performance_preference: balance_power

  # Mount openebs-hostpath in kubelet
  - |-
    machine:
      kubelet:
        extraMounts:
          - destination: /var/openebs/local
            type: bind
            source: /var/openebs/local
            options: ["bind", "rshared", "rw"]

  # Mount Longhorn storage in kubelet
  - |-
    machine:
      kubelet:
        extraMounts:
          - destination: /var/lib/csi-local-hostpath
            type: bind
            source: /var/lib/csi-local-hostpath
            options: ["bind", "rshared", "rw"]

  # # Mount 2nd disk for Longhorn Storage
  - |-
    machine:
      disks:
      - device: /dev/nvme0n1
        partitions:
          - mountpoint: /var/lib/csi-local-hostpath

  # # Disable predictable NIC naming
  # - |-
  #   machine:
  #     install:
  #       extraKernelArgs:
  #         - net.ifnames=0

  # # Performance hacks
  - |-
    machine:
      install:
        extraKernelArgs:
          - apparmor=0
          - init_on_alloc=0
          - init_on_free=0
          - mitigations=off
          - security=none

controlPlane:
  nodeLabels:
    topology.kubernetes.io/zone: controlPlane
  patches:
    # Cluster configuration
    - |-
      cluster:
        allowSchedulingOnMasters: true
        controllerManager:
          extraArgs:
            bind-address: 0.0.0.0
        coreDNS:
          disabled: true
        proxy:
          disabled: true
        scheduler:
          extraArgs:
            bind-address: 0.0.0.0
          config:
            apiVersion: kubescheduler.config.k8s.io/v1
            kind: KubeSchedulerConfiguration
            profiles:
              - schedulerName: default-scheduler
                pluginConfig:
                  - name: PodTopologySpread
                    args:
                      defaultingType: List
                      defaultConstraints:
                        - maxSkew: 1
                          topologyKey: kubernetes.io/hostname
                          whenUnsatisfiable: ScheduleAnyway

    # ETCD configuration
    - |-
      cluster:
        etcd:
          extraArgs:
            listen-metrics-urls: http://0.0.0.0:2381
          advertisedSubnets:
            - "10.69.1.0/24"

    # Disable default API server admission plugins.
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl

    # Enable K8s Talos API Access
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:admin
            allowedKubernetesNamespaces:
              - kube-tools

    # Enable hostDNS:
    - |-
      machine:
        features:
          hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
            resolveMemberNames: true

worker:
  nodeLabels:
    topology.kubernetes.io/zone: worker
