apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secrets-manager
spec:
  refreshInterval: 15
  provider:
    webhook:
      url: "http://${PI_IP}:5000/key/{{ .remoteRef.key }}"
      headers:
        Authorization: "Bearer {{ print .serviceaccount.token }}"
      # result:
      #   jsonPath: "$.value.{{ .remoteRef.property }}"
      result:
        jsonPath: "$.value"
      secrets:
      - name: serviceaccount
        secretRef:
          name: bws-secret
          key: token
          namespace: external-secrets
