---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actions-runner-controller.yaml
  - ./authentik-charts.yaml
  - ./backube.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./coredns.yaml
  - ./crunchydata.yaml
  - ./descheduler.yaml
  - ./dragonfly.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./grafana.yaml
  - ./homepage.yaml
  - ./ingress-nginx.yaml
  - ./intel.yaml
  - ./itzg.yaml
  - ./jetstack.yaml
  - ./kubernetes-sigs-nfd.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./piraeus.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./rook-ceph.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./userinit-controller.yaml
  - ./weave-gitops.yaml
