---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        TUNNEL_ID: "{{ .CLUSTER_CLOUDFLARE_TUNNEL_ID }}"
        credentials.json: |
          {
            "AccountTag": "{{ .CLOUDFLARE_ACCOUNT_TAG }}",
            "TunnelSecret": "{{ .CLOUDFLARE_TUNNEL_SECRET }}",
            "TunnelID": "{{ .CLUSTER_CLOUDFLARE_TUNNEL_ID }}"
          }
  data:
    - secretKey: CLOUDFLARE_ACCOUNT_TAG
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 136c1200-904a-4e3c-bd02-ac6e00f706e3
        property: account_id
    - secretKey: CLOUDFLARE_TUNNEL_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 136c1200-904a-4e3c-bd02-ac6e00f706e3
        property: tunnel_secret
    - secretKey: CLUSTER_CLOUDFLARE_TUNNEL_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 136c1200-904a-4e3c-bd02-ac6e00f706e3
        property: tunnel_id
