---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: mc-router
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "disabled"
spec:
  endpoints:
    - dnsName: "mc.${SECRET_DOMAIN}"
      recordType: CNAME
      targets: ["ipv4.${SECRET_DOMAIN}"]
