---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings-utility
  namespace: flux-system
data:
  ## Utility cluster settings
  CLUSTER: utility
  BITWARDEN_CABUNDLE: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJvVENDQVVlZ0F3SUJBZ0lSQUl2b3I2eGJ2d2pqU1RVM3UrOHhxQm93Q2dZSUtvWkl6ajBFQXdJd01ERVIKTUE4R0ExVUVDaE1JYW05eWVTNWtaWFl4R3pBWkJnTlZCQU1URW1odmJXVXRjMlZzWm5OcFoyNWxaQzFqWVRBZQpGdzB5TkRBM01UUXdNalF6TVRaYUZ3MHlOREV3TVRJd01qUXpNVFphTURBeEVUQVBCZ05WQkFvVENHcHZjbmt1ClpHVjJNUnN3R1FZRFZRUURFeEpvYjIxbExYTmxiR1p6YVdkdVpXUXRZMkV3V1RBVEJnY3Foa2pPUFFJQkJnZ3EKaGtqT1BRTUJCd05DQUFUM1hqUTZ0eG5KZCtkWis1VzFUbHp5UTlZYzdsRTNyKysxaS82M3pOcWg0RHFXaHMzKwpkZXNxbnNzVTBlc3h3bDh6WENacGJKY0hkQUpMbGpyR0RERG5vMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBcVF3CkR3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVRMbzRoWjk0OE5oL2JqOTRvYWNNT290c1dQa3cKQ2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnQzBucUptVDUxWWp4UFRrbERwYXlIMHpHV3kwOThYTWJTK0prZWhBUApVYkVDSVFENHFxZHRxd2NXZUdjWlZmeE9YTUVJbVc4dnlGSUVlTTlmV1FrZ3BteE9SZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  PVC_VOLSYNC_STORAGECLASS: longhorn
  VOLSYNC_SNAPSHOTCLASS: longhorn-snapclass
  VOLSYNC_CACHE_SNAPSHOTCLASS: longhorn-cache
  VOLSYNC_STORAGECLASS: longhorn-snapshot
