apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-utility
stringData:
    #ENC[AES256_GCM,data:xxnbfu67wgLvZ0PqTcNN0Q==,iv:LasA5aqx6l471zjQEEVJuPHGUWr+meE1DKMask3+Zb4=,tag:hgtvtQXcoMaInOpBa++mgw==,type:comment]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ML50Qq14IREwEbAM/N1JOKRZqfBcNa3zQGyy3cLXn3Mpn8nY,iv:lj5fvYFno80fnNu/tgD8UKPPAC1AnuMtQcS/D2rMTTU=,tag:kVGtheTEWcMRQEp/2yTtlA==,type:str]
    SVC_NGINX_INTERNAL: ENC[AES256_GCM,data:ilfw6QhaTh0U7UU=,iv:eJ7/LGu8IZZjWJvDcl0DCAiavC8gf0gO8MTyQ04q3Ck=,tag:Feg8UOuivAv2gyeSh4OuCA==,type:str]
    SVC_NGINX_EXTERNAL: ENC[AES256_GCM,data:EEnrrSfroxhmdK0=,iv:A2CoFRYWGqyWYD/825xZ62Ppl9Rd1fAdDTC1iIoCFEE=,tag:DBn3cz0JIFxlbQILnLoegw==,type:str]
    SVC_HOME_ASSISTANT_ADDR: ENC[AES256_GCM,data:KlS7OuwdThCf8qg=,iv:Tv51Qc+2q2jmm83YfpKwcqJCOVap9WACE7yTrpvr9h0=,tag:Sk7GdOaHC9NORZIGsxlCxg==,type:str]
    SVC_MQTT_ADDR: ENC[AES256_GCM,data:JLe9yBBRNm4rQ3Y=,iv:35bLdpiBgXNeWPMYpAY6ehGBQVeZh3HZpMMyzXeqq0I=,tag:AaH6B2ycs0ZZARXGaYuu+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12v9uw8k6myrr49z9aq6jmcwa79aepu0p6p462nrv968qcae72pcspwldec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SnlFNVh6cDhuaXdSdXg1
            a2IwUXFvejRQc2Z6NlR4ak5pdWJ5Q1JtU3pjCldleml5RXA4Tk5wc3VQZW5kNXlm
            enpieDhJL3dUQkxKQ2hKVldiTFhGa2MKLS0tIFV2ZWFJTGVodmNhS0FUQzZMbExY
            ZjkzSGxlT1R6VHNHNDVNb3hBVzNVZ3MKMtBhVS0FKr6NWqv9S6mSOhjCDIdO3uNz
            OS9Qh8tX5J/s1ZH6z3/DNLWKonA6mccm1kH7jNQe/+w4ozYxa4me9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-12T19:20:48Z"
    mac: ENC[AES256_GCM,data:NpdrY4lLfAPTqclo9Si+j+3IWkN285B7EG2Ou78W9n01UB+RlI0v1lKPp9sAtXvtyq9WTMcMnhKfJoSoFjR6TQKOcXOun7txJ/aedQr/ZGnfAMtLOR080zm7B0ASBi+U5kuSo2B+0qUkKfcmteuTcW+eSZXKiXY89aMYixAbuV4=,iv:xf15eNdrOvBS7q9BZ7AHZfCcUD6XGPF8K42IQ0ctO/U=,tag:i/Jg1Zbj/SUY1ZjJjHpgoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
