---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.1/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app nut-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: *app
    controllers:
      mnut-exporterain:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/druggeri/nut_exporter
              tag: "3.1.1"
            env:
              TZ: ${TIMEZONE}
            args:
              # the first time I set this, the first and last entries were ignored, so I have doubled them.
              - --nut.vars_enable="battery.charge,battery.charge,battery.runtime,battery.voltage,battery.voltage.nominal,input.voltage,input.voltage.nominal,output.voltage,output.voltage.nominal,ups.realpower,ups.load,ups.status,ups.status"
            resources:
              limits:
                cpu: 50m
                memory: 100Mi
    service:
      app:
        controller: *app
        ports:
          metrics:
            enabled: true
            protocol: TCP
            port: 9199
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "exporters.${CLUSTER_DOMAIN}"
