---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  ## Shared
  TIMEZONE: "America/Edmonton"
  CLUSTER_CIDR: "10.42.0.0/16"
  NODE_CIDR: "10.69.1.0/24"
