apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:NjqWHkgbbg==,iv:CBRJ+Xn/pzDUgOGrfd6nBfYXfvf929FqdnFM6KZszf4=,tag:J7UyNa77ISnedc9eDJaBVA==,type:comment]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:22kLRx961fV93eFXrw==,iv:vR8AYz5+5gOVT5/j6KXlI5ZaDkFtgNuNTUiyajWWjpg=,tag:z6SmHkEL69t9Hx6xgF/liA==,type:str]
    BITWARDEN_ORG: ENC[AES256_GCM,data:z7yTQqA9PNtP5Iwx/aTNFkYGEM0L0PEUAyPVT3Uh/T8Wqkpl,iv:jZa2PKGmWRaZQTrnWXvw2n2ZX2Cf3Ar5MeA5vzd4P+c=,tag:G7kT1e/SBuKe872ck/Nx0g==,type:str]
    BITWARDEN_PROJ: ENC[AES256_GCM,data:NPlKtT5Esv/QZRfv8ZFFa/EUoG7IKBdv1Jf5rMC0tmhZaNcG,iv:zU5CroAa5rp82TJ9jbmHMnqCFgs8r0oSUKp9ddl/vPI=,tag:JAHHfzuiQTWCMLQajhImZw==,type:str]
    CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:pGi5nknmvN6zwuliILXXXPde2gMHRdQI8zJDebzRSPQ=,iv:XpaO0SJ3O2trirWZ50WqV+BNTlnTS9oA1vpquTgzxD0=,tag:5A2BMQZ/nyO5kakMowBVWw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:Ulc4QMnUa3g=,iv:wAJV0i1bjV+/grFguyaSE45+SXemSvmBbq5UIkeEO0Y=,tag:ae5kL99lzMxi8X1fTaTQLw==,type:str]
    SVC_NUT_ADDR: ENC[AES256_GCM,data:wQejmnD1yHg9NTg=,iv:bRLR2FzSq6okzy+RaHtPjE4a2g6dYVwxcWPgO9FrhMA=,tag:a3N2mkNaIoe+kzphD8LeYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12v9uw8k6myrr49z9aq6jmcwa79aepu0p6p462nrv968qcae72pcspwldec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NWNTRmtma01pMFY3Ny93
            N2F5bTZFc0ZKYm5hWHp6bENndktxRXNBa1F3CnBNVXJldG9ZR0cwcXQrcjc5UTNu
            dlpJNEZ5eVhIdkwvRE5ubUNBQjhnWTQKLS0tIDhzRGZTdWFKak5PNmVnbG5hckl3
            Mml3TDJwa2tWTUV3d0piVTFJSFhhOEEKr0FLybpRsnIlbT55No+/qolp2GVAB1yD
            yeGYjULaarqScUazhWSnuzDcRj4X0MX8UDV5lc4OsGba9ymVbywDbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-12T16:39:51Z"
    mac: ENC[AES256_GCM,data:zPZ5EyfCEUUP2thWkJJ11PcitA6C7Uvllir6iY9EBEi2uRBPPmT16AJFQldb44VHTlXrExJpWrU6iZsw6LVQbcQWiWrDadskNgAkK24sMnGyzxqMr521Y1iegRomfoOGMFxUWVvh0HaKGH4ol8tZPAh5eo6q/LYZGhzVlbQC+0k=,iv:2DGCakt2OeYaCR8qVDeySgTNgXKWFZiPCRnQo6W7WDw=,tag:Dt5qL50Xg9/vDNmh7w+97g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
