---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./alertmanager/ks.yaml
  - ./gatus/ks.yaml
  - ./goldilocks/ks.yaml
  - ./grafana/ks.yaml
  - ./karma/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./kube-state-metrics/ks.yaml
  - ./loki/ks.yaml
  - ./node-exporter/ks.yaml
  - ./nut-exporter/ks.yaml
  - ./speedtest-exporter/ks.yaml
  - ./thanos/ks.yaml
  - ./unifi-poller/ks.yaml
  - ./vector/ks.yaml
  - ./vpa/ks.yaml
