---
kubernetes:
  vars:
    ansible_user: vetrius
    ansible_ssh_port: 22
  children:
    master:
      hosts:
        bronya:
          ansible_host: 192.168.3.11 #RPi5 8GB
        himeko:
          ansible_host: 192.168.3.12 #RPi5 8GB
        jingliu:
          ansible_host: 192.168.3.13 #RPi4 8GB
    worker:
      hosts:
        kafka:
          ansible_host: 192.168.3.14 #RPi4 8GB
