---
kubernetes:
  vars:
    ansible_user: vetrius
    ansible_ssh_port: 22
  children:
    master:
      hosts:
        fuxuan:
          ansible_host: 192.168.3.10
    worker:
      hosts:
        jingliu:
          ansible_host: 192.168.3.11
        kafka:
          ansible_host: 192.168.3.12
        seele:
          ansible_host: 192.168.3.13
