---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
  - ./local-path-provisioner/ks.yaml
  - ./snapshot-controller/ks.yaml
  - ./volsync/ks.yaml
components:
  - ../../../shared/components/alerts
  - ../../../shared/components/namespace
