---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name radarr-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # App
        RADARR__API_KEY: "{{ .RADARR_API_KEY }}"
        RADARR__POSTGRES_HOST: &dbHost postgres-rw.database.svc.cluster.local
        RADARR__POSTGRES_PORT: "5432"
        RADARR__POSTGRES_USER: &dbUser "{{ .POSTGRES_USERNAME }}"
        RADARR__POSTGRES_PASSWORD: &dbPass "{{ .POSTGRES_PASSWORD }}"
        RADARR__POSTGRES_MAIN_DB: radarr_main
        RADARR__POSTGRES_LOG_DB: radarr_log
        # Postgres Init
        INIT_POSTGRES_DBNAME: radarr_main radarr_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
  - extract:
      key: radarr
  - extract:
      key: cloudnative-pg
