---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/onedr0p/plex
      tag: 1.32.6.7557-1cf77d501@sha256:7cc587ba32ba8b1f00b0f1b6bd07d8d6290e6e06c5bb05ea00cd5e9f13bbd40c
    env:
      TZ: ${TIMEZONE}
    service:
      main:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: "${SVC_PLEX_ADDR}"
        externalTrafficPolicy: Cluster
        ports:
          http:
            port: 32400
    ingress:
      main:
        enabled: true
        ingressClassName: external
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: plex.png
          gethomepage.dev/name: Plex Kubernetes
          gethomepage.dev/group: Media
          gethomepage.dev/widget.type: plex
          gethomepage.dev/widget.url: http://plex.media.svc.cluster.local:32400
          gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_PLEX_TOKEN}}"
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups:
        # - 44
        - 105
        # - 65539

    nodeSelector:
      node-role.kubernetes.io/worker: "true"
      intel.feature.node.kubernetes.io/gpu: "true"

    resources:
      requests:
        cpu: 100m
        gpu.intel.com/i915: 1
        memory: 4G
      limits:
        gpu.intel.com/i915: 1
        memory: 16G
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 20Gi
        storageClass: longhorn-plex
    persistence:
      media:
        enabled: true
        existingClaim: media
        mountPath: /data
        subPath: media
      transcode:
        enabled: true
        type: emptyDir
      plex-profile:
        enabled: true
        type: configMap
        name: plex-profile-configmap
        subPath: Chromecast.xml
        mountPath: /usr/lib/plexmediaserver/Resources/Profiles/Chromecast.xml
        readOnly: true
