---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name node-exporter
spec:
  staticConfigs:
    - targets:
        - voyager.internal:9100
        - pikvm.internal:9100
        - pompom.internal:9100
        - amber.internal:9100
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name pikvm
spec:
  staticConfigs:
    - targets: ["pikvm.internal"]
  metricsPath: /api/export/prometheus/metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name blocky
spec:
  staticConfigs:
    - targets:
        - blocky.${INTERNAL_DOMAIN}
        - blocky.${SECRET_DOMAIN}
        - amber.internal:4000
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name minio-job
spec:
  staticConfigs:
    - targets: ["s3.jory.dev"]
  metricsPath: /minio/v2/metrics/cluster
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
