# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./abiotic/ks.yaml
  # - ./core-keeper/ks.yaml
  - ./minecraft/ks.yaml
  # - ./palworld/ks.yaml
  - ./space-engineers/ks.yaml
