---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kube-prometheus-stack
spec:
  target:
    deletionPolicy: Delete
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      type: Opaque
      data:
        objstore.yml: |-
          type: s3
          config:
            bucket: thanos
            endpoint: rook-ceph-rgw.{{ .PRIMARY_DOMAIN }}
            access_key: {{ .AWS_ACCESS_KEY_ID }}
            secret_key: {{ .AWS_SECRET_ACCESS_KEY }}
  data:
    - secretKey: PRIMARY_DOMAIN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 136c1200-904a-4e3c-bd02-ac6e00f706e3
        property: primary_domain
    - secretKey: secret_key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 69af7022-f28c-4152-90a7-b0560025eaa7
        property: password
    - secretKey: endpoint
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 69af7022-f28c-4152-90a7-b0560025eaa7
        property: password
