---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/k8s.bitwarden.com/bitwardensecret_v1.json
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: cloudflare-test-secret
spec:
  organizationId: ${BITWARDEN_ORG}
  secretName: cloudflare-test-secret
  map:
    - bwSecretId: 63e5956e-f276-4a25-a5c0-b11300f4075c
      secretKeyName: cloudflare
  authToken:
    secretName: bw-auth-token
    secretKey: token
