apiVersion: v1
kind: Secret
metadata:
    name: bw-auth-token
stringData:
    token: ENC[AES256_GCM,data:5uLuPCZXGNrrUJT/nJXFs/OnlsUCyjFGp4BJXJZzlaaVmTb/Q1vyNdVa+Eaugh5u2d0mjlKLSvZ9pF0EieMUJemccdmPSxPdpHz6vqb9bOCAoOSQSgeU159082ImBQ==,iv:wVoOiHN33uraDMH/YJDE5Is44ky1wx5M1CBA/9B3BcA=,tag:BAlI0Ds1PCs3BKWU+BUEpg==,type:str]
    ORG_ID: ENC[AES256_GCM,data:aGlQ8/D62t0cJmuPHs+tAkOtBzhg9I0bpufqooM/8K6oPtHs,iv:iGzlZmIb14o2BHfMjtcGTMnBf11OOSfFdTVKb/YDQY4=,tag:EuivYmi6VNynh3qt6B1q1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12v9uw8k6myrr49z9aq6jmcwa79aepu0p6p462nrv968qcae72pcspwldec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWVR4eGJYWUJ1V0F4Z2x0
            NW8wbFQrY1YxakY3RGtuQmozbFlyL0NqekVzCmZXNWFBdVg5RlBtdUp1dHVFWDlm
            ZVlGOXRjUGpJRm1rMzh1ck5BSVhadmsKLS0tIGVqeE5HUnZVczl4NkJmNEJ1NVoz
            KzRDbWFsVEpsalByQ1pKL2VsbHZuaTQKKQ+Ia4b12/kVhKvypUlf/riQuTQFh9zy
            T/Lp0g6o1eW7KoE+tFk9QgPGYLphyXn/iVNWpz+bMTXhcgFL0qTQZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-07T15:16:54Z"
    mac: ENC[AES256_GCM,data:e5yI6pUMa5N0+lGsaWXkyuY4SzrbR2WPCAX0KGtdGZhfC7y81cheOpxJ+msUPZ5tUC10FFZPj0hT+UHAUpB1O3pxM6QfAKD6CVVD32axwb+yV7QwxWoxnF2kMy8+15wf10//G1BUIWKXCyhTAGIRyXDszG3iu2q++8mdbQgK7k4=,iv:TwTebQopf9ahwyH/Kh9ldL8Ku9sEyn6SEaHgEm0YTZ4=,tag:BOEDCHdsyNCKNWT5BcOptw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
