---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name vrising-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        VR_PASSWORD: "{{ .VR_PASSWORD }}"
        VR_SERVER_NAME: "{{ .VR_SERVER_NAME }}"
        VR_LOWER_FPS_WHEN_EMPTY: "{{ .VR_LOWER_FPS_WHEN_EMPTY }}"
        VR_SECURE: "{{ .VR_SECURE }}"
        VR_DIFFICULTY_PRESET: "{{ .VR_DIFFICULTY_PRESET }}"
        SERVERNAME: "{{ .VR_SERVER_NAME }}"
  dataFrom:
  - extract:
      key: vrising
