---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: self-hosted
resources:
  - ./actual/ks.yaml
  - ./atuin/ks.yaml
  - ./homepage/ks.yaml
  - ./lubelog/ks.yaml
  - ./paperless/ks.yaml
  - ./redlib/ks.yaml
components:
  - ../../../shared/components/alerts
  - ../../../shared/components/namespace
patches:
  - # Add the name to the namespace
    patch: |
      - op: add
        path: /metadata/name
        value: self-hosted
    target:
      kind: Namespace
