---
certManager:
  enabled: true
configMaps:
  - create: true
    name: cluster-settings
    data:
      CLUSTER: main
      PVC_VOLSYNC_STORAGECLASS: ceph-block
      VOLSYNC_SNAPSHOTCLASS: csi-ceph-blockpool
      VOLSYNC_CACHE_SNAPSHOTCLASS: ceph-block
      VOLSYNC_STORAGECLASS: ceph-block
secrets: []
