---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mc-router
spec:
  interval: 5m
  chart:
    spec:
      chart: mc-router
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: itzg-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    services:
      minecraft:
        type: LoadBalancer
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Service
              name: mc-router
            patch: |
              apiVersion: v1
              kind: Service
              metadata:
                name: ignored
                annotations:
                  io.cilium/lb-ipam-ips: "${SVC_MINECRAFT_ADDR}"
                  external-dns.alpha.kubernetes.io/hostname: mc.${SECONDARY_DOMAIN}