apiVersion: v1
kind: Secret
metadata:
    name: discord-rss-notifier-secret
stringData:
    config.toml: ENC[AES256_GCM,data:EKe1F2VOr023Zygj7E5fAukDjP/+vrWkqmbFB9OH+z8Kq3QLlSKTVU9t+zdcCBkOhpopgU7A9JDc+tojXQ20bOHQG4CUoHzfyTgzn1MFBDwtnI5xNFLgbU1SFlWUJuspzTy8JKlU4ocd7HE5WDwVQIKsRR8b74Sd06fMV2WJdHVJyKl638lu9waTy6lElNvscKjGLvysNgunMpPNgVJOGHsBlgMl0NPb2vaxoivJmoKuYISatKOQWWZOnkbpwzCyez9LC/VdKWLKoa+fp/A/Y32I5/Yh7KyRfPWeMQ32umtUjva8hIKKIOM8addIqEDiwJK4n2QHgSX0KJdIh66UJKC49lUyCccgpxm5Jar1+oR41ACyxV0GLHaUBcSu8Bk4rsuLoILthj+s9aKqpttpGv+tYBSi6B7e72ZIPfvK+lG8N2ufF+AFM/aWFvozSQTRRmEnQ04bK3d1JWHCyoe1WNjPgbHASxXd2VvoQ1rufrX7WFSAJIueABGbYmmubFmHVWrL8XTEaYcR32sbo4faysz8sFYfLGGKL6CrTa3UNwxB8VqBfZGAqrOlVB5hm9miyJvORjymZCxjU3vEkZA8YsJ+AAOn0YmF/447X4Z1sb6Em24Av0FDLLCkyvl+hC6OK7v1mCsfBflGPN3eZKwY0WOFcFjefOj9hqmruJHX/i3E8if3DWiCgdNi4tyDNQxZU0OZ894h81d31luJd6a1ipp8C+WwwshD1X/QgC8fuLDYyDWHuVoVrLrHVyyfBOXc,iv:Pwkbwf2lcE1i/db7sWQLoJirZr5ITqd8LWEkHOYfUFk=,tag:fq4ODk2XvN9MaGiFduf6lg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12v9uw8k6myrr49z9aq6jmcwa79aepu0p6p462nrv968qcae72pcspwldec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPR043QmRUaERvYm0reS9O
            UnY5N1dsMUo3Ukt1eDZ0eHQyZnJEY215b1gwCk9JYzlrdzNKbEZPN2VUandIK1lK
            SDJaRFFRckRnSkFlYWZyTDhNN2YvUE0KLS0tIG1sMVJaK1oxUHhPRS9hQlN4NHY2
            MXhhUlRQOHk2c1lMYWIxMWswVThlZ3MKjpzO4QpjDbUu1jHucRN5T6nZ/nv7zMfd
            8TjLg6eo/NmZOrpCVkQmKeuLTIrVw4STQ9xkz3MUjt4203K4cKq24Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-08T17:53:35Z"
    mac: ENC[AES256_GCM,data:TNtT8uCuV81Nh0e+FogXdMqOem4FA55SkzqVHtp9OD3xWr9DvoTCFJk9/Ybwod3UbbvuZhBVFBjJadZbs8o5ZHZyHSEUgf0jhgPxMApsmKq8H/ktd2QBaFFMuYB06y2SLQFpHzzSVn39ghMZb/CmrEaqDlbGNQI9YOt2MhklVKg=,iv:Qbe5M5xUtXhGdXtvc2+LRuapWffZB2rXczOcGVlN0J8=,tag:Ezn/q83LPAp1k6LnEjIzqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
