# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rss-forwarder
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/morphy2k/rss-forwarder
              tag: 0.7.0-beta.3@sha256:51391a60196d5c07f97b4efa59743bc08fe87302047869553fa49bda900fb8a8
            env:
              TZ: "${TIMEZONE}"
            probes:
              liveness: &disabled
                enabled: false
              readiness: *disabled
              startup: *disabled
            resources:
              requests:
                cpu: 5m
              limits:
                memory: 128M
    service:
      main: *disabled
    ingress:
      main: *disabled
    persistence:
      config:
        enabled: true
        type: secret
        name: rss-forwarder
        globalMounts:
        - path: /data/config.toml
          subPath: config.toml
          readOnly: true
