---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app plex
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../../shared/components/gatus/external
    - ../../../../../shared/components/volsync
  dependsOn:
    - name: onepassword-store
    - name: volsync
  interval: 30m
  path: ./kubernetes/main/apps/media/plex/app
  postBuild:
    substitute:
      APP: *app
      GATUS_PATH: /web/index.html
      VOLSYNC_CAPACITY: 50Gi
      VOLSYNC_CACHE_CAPACITY: 25Gi
  prune: false # revert to true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: false
  targetNamespace: media
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kometa
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../../shared/components/volsync
  dependsOn:
    - name: plex
    - name: tautulli
    - name: radarr
    - name: sonarr
    - name: onepassword-store
    - name: volsync
  interval: 30m
  path: ./kubernetes/main/apps/media/plex/kometa
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 10Gi
  prune: false # revert to true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  timeout: 5m
  wait: false
# ---
# # yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &app movie-roulette
#   namespace: flux-system
# spec:
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *app
#   components:
#     - ../../../../../shared/components/gatus/external
#     - ../../../../../shared/components/volsync
#   dependsOn:
#     - name: plex
#   interval: 30m
#   path: ./kubernetes/main/apps/media/plex/movie-roulette
#   postBuild:
#     substitute:
#       APP: *app
#   prune: false # revert to true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   targetNamespace: media
#   timeout: 5m
#   wait: false
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app plex-auto-languages
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: plex
  interval: 30m
  path: ./kubernetes/main/apps/media/plex/plex-auto-languages
  prune: false # revert to true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app plex-image-cleanup
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: plex
    - name: onepassword-store
  interval: 30m
  path: ./kubernetes/main/apps/media/plex/plex-image-cleanup
  postBuild:
    substitute:
      APP: *app
  prune: false # revert to true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  timeout: 5m
  wait: false
