---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minecraft
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        RCON_PASSWORD: "{{ .RCON_PASSWORD }}"
  data:
    - secretKey: RCON_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 012c4102-c0bf-488c-9e3b-b0cb0156b928
        property: password
