---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        api-token: "{{ .api_token }}"
  data:
    - secretKey: api_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 136c1200-904a-4e3c-bd02-ac6e00f706e3
        property: api_token
