---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app mylar
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: longhorn
      namespace: storage
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/linuxserver/mylar3
              tag: version-v0.7.6@sha256:ae9c057e845d6ca7c9159499ec285117019c39ac8a8b033931f5e1525d50535e
            env:
              TZ: ${TIMEZONE}
              UID: 1000
              GID: 1000
            resources:
              requests:
                cpu: 15m
                memory: 700M
              limits:
                memory: 1200M
    service:
      main:
        ports:
          http:
            port: 8090
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Downloads
          gethomepage.dev/name: Mylar
          gethomepage.dev/icon: mylar.png
          gethomepage.dev/widget.type: mylar
          gethomepage.dev/widget.url: http://mylar.downloads:8090
          gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_MYLAR_TOKEN}}"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_DOMAIN}/css/base/mylar/nord.css"></head>';
            sub_filter_once on;
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: *app
      data:
        enabled: true
        type: nfs
        server: ${NAS_IP:=temp}
        path: ${SECRET_NFS_DATA:=temp}
        globalMounts:
          - path: /data
