apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:BblSQWWP0PpyvVNEad00sMs2vQ1R5s07CwHEymi0ldS+f91z9wJtdA==,iv:rGNipefpWtKGRkQqSGuAMtFew4rlRBmphPxBoMSVw5w=,tag:0OnJoWDWqqx0vRJQVXZojg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12v9uw8k6myrr49z9aq6jmcwa79aepu0p6p462nrv968qcae72pcspwldec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLczJLTXlhL1d0TUw1RmIw
            YkF2MGVFa00xQ3lTanI2cjkwR2dCc05WbW4wCkh4N1NhWmJjYm5BdVg1T1lvalU5
            STdXSFFFc1dLaFpWbXRXaTY3SFNURncKLS0tIE91ZVc4S0gvTVNWRHpWaEZJdzZi
            L1YrajFWSVR3ZmZRRktsNmhac3hnNTAKQ8Y9GqFsIZND7qXfDObTGzOKhn/tXn7i
            s6HawJ1gRsYzUVer2zpIWF9u5DkQIuR4dvFFoC9XfGnmba09WFaFkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-24T16:09:41Z"
    mac: ENC[AES256_GCM,data:ytQ9X1aoU0Ns0DMCzwxGoIvsQLtzVSVsaBXAhprMn1Eni1zvQCn0qwHD/U2P4Wa/trT8B3dfafpUg8EvpvMDgrC82XOL4ZLnxVHctWxQmbGk2mfEqPU/p1k071z91Luryig0uuoodzWtFAuOfLfGTfW9+MK+ptC7gEuAIZgRgiI=,iv:iBhhsg2otQVxRLC/AQpbFX5IRWNgM13dVx78ZMqmPdc=,tag:s2L2gUUDCfkUdR0TOWtIdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
