---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name plex-meta-manager-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      data:
        MDBLIST_API_KEY: "{{ .MDBLIST_API_KEY }}"
        MYANIMELIST_ACCESS_TOKEN: "{{ .MYANIMELIST_ACCESS_TOKEN }}"
        MYANIMELIST_CLIENT_ID: "{{ .MYANIMELIST_CLIENT_ID }}"
        MYANIMELIST_CLIENT_SECRET: "{{ .MYANIMELIST_CLIENT_SECRET }}"
        MYANIMELIST_EXPIRES_IN: "{{ .MYANIMELIST_EXPIRES_IN }}"
        MYANIMELIST_LOCALHOST_URL: "{{ .MYANIMELIST_LOCALHOST_URL }}"
        MYANIMELIST_REFRESH_TOKEN: "{{ .MYANIMELIST_REFRESH_TOKEN }}"
        OMDB_API_KEY: "{{ .OMDB_API_KEY }}"
        PLEX_API_KEY: "{{ .PLEX_TOKEN }}"
        RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
        SONARR_API_KEY: "{{ .SONARR_API_KEY }}"
        TAUTULLI_API_KEY: "{{ .TAUTULLI_API_KEY }}"
        TMDB_API_KEY: "{{ .TMDB_API_KEY }}"
        TRAKT_ACCESS_TOKEN: "{{ .TRAKT_ACCESS_TOKEN }}"
        TRAKT_CREATED_AT: "{{ .TRAKT_CREATED_AT }}"
        TRAKT_CLIENT_ID: "{{ .TRAKT_CLIENT_ID }}"
        TRAKT_CLIENT_SECRET: "{{ .TRAKT_CLIENT_SECRET }}"
        TRAKT_EXPIRES_IN: "{{ .TRAKT_EXPIRES_IN }}"
        TRAKT_REFRESH_TOKEN: "{{ .TRAKT_REFRESH_TOKEN }}"
  dataFrom:
  - extract:
      key: kometa
  - extract:
      key: plex
  - extract:
      key: tautulli
  - extract:
      key: radarr
  - extract:
      key: sonarr
