---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app bazarr
  namespace: flux-system
spec:
  targetNamespace: downloads
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: crunchy-postgres-operator-cluster
    - name: crunchy-postgres-stores
    - name: onepassword-store
    - name: volsync
  path: ./kubernetes/main/apps/downloads/bazarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false # no flux ks dependents
  interval: 30m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app whisper
  namespace: flux-system
spec:
  targetNamespace: downloads
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/main/apps/downloads/bazarr/whisper
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false # no flux ks dependents
  interval: 30m
  timeout: 5m
