---
version: "3"

tasks:

  push:
    desc: Push all kubeconfig to OnePassword
    cmds:
      - task: push-pi5
    preconditions:
      - op user get --me

  push-pi5:
    desc: Push pi5 kubeconfig/talosconfig to OnePassword
    cmds:
      - op item edit kubernetes KUBECONFIG_PI5[text]="$(cat {{.ROOT_DIR}}/kubernetes/pi5/kubeconfig)" &>/dev/null
      - op item edit kubernetes TALOSCONFIG_PI5[text]="$(cat {{.ROOT_DIR}}/kubernetes/pi5/bootstrap/talos/clusterconfig/talosconfig)" &>/dev/null
      - op item edit kubernetes TALOSCONFIG_PI5_BASE64[text]="$(cat {{.ROOT_DIR}}/kubernetes/main/bootstrap/talos/clusterconfig/talosconfig | base64 -w 0)" &>/dev/null
    preconditions:
      - op user get --me

  pull:
    desc: Pull Kubeconfig from OnePassword
    cmds:
      - mkdir -p {{.ROOT_DIR}}/kubernetes/pi5/bootstrap/talos/clusterconfig/
      - op item get kubernetes --fields label=KUBECONFIG_PI5 | tr -d '"' > {{.ROOT_DIR}}/kubernetes/pi5/kubeconfig # Pi5 kubeconfig
      - op item get kubernetes --fields label=TALOSCONFIG_PI5 | tr -d '"' > {{.ROOT_DIR}}/kubernetes/pi5/bootstrap/talos/clusterconfig/talosconfig # Pi5 talosconfig
    preconditions:
      - op user get --me
