---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/infra.contrib.fluxcd.io/terraform_v1alpha2.json
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: minio
spec:
  interval: 12h
  approvePlan: auto
  backendConfig:
    customConfiguration: |
      backend "s3" {
        bucket = "terraform-state"
        key    = "minio/minio.tfstate"

        region                      = "main"
        skip_credentials_validation = true
        skip_metadata_api_check     = true
        skip_region_validation      = true
        force_path_style            = true
      }
  backendConfigsFrom:
  - kind: Secret
    name: terraform-backend-secret
  path: ./minio
  sourceRef:
    kind: OCIRepository
    name: terraform
    namespace: flux-system
  runnerPodTemplate:
    spec:
      image: ghcr.io/lildrunkensmurf/tf-runner-bitwarden:0.15.1@sha256:042f611c864181d7342edb8442f5c32b778fd5f91abad348ae636803960d0f9b
  varsFrom:
    - kind: Secret
      name: terraform-minio-secret
