# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/infra.contrib.fluxcd.io/terraform_v1alpha2.json
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: minio
spec:
  interval: 12h
  approvePlan: auto
  backendConfig:
    customConfiguration: |
      backend "s3" {
        bucket = "terraform-state"
        key    = "minio/minio.tfstate"
        region                      = "main"
        skip_credentials_validation = true
        skip_metadata_api_check     = true
        skip_region_validation      = true
        force_path_style            = true
      }
  backendConfigsFrom:
  - kind: Secret
    name: terraform-backend-secret
  path: ./minio
  sourceRef:
    kind: OCIRepository
    name: terraform
    namespace: flux-system
  runnerPodTemplate:
    spec:
      image: ghcr.io/lildrunkensmurf/tf-runner-bitwarden:0.15.1@sha256:666873ebdaa810c4a4dc249739d5a5928922d0e491f25f3e340ec620b751196a
      # Working image 1.3.9: ghcr.io/lildrunkensmurf/tf-runner-bitwarden:0.15.1@sha256:f783ebe9559a2c39416f2fa5e48e1c126fa9ab4d32324bda51e340f866e4837c
  varsFrom:
  - kind: Secret
    name: terraform-minio-secret
