apiVersion: v1
kind: Secret
metadata:
    name: bitwarden-access-token
stringData:
    token: ENC[AES256_GCM,data:cgZoXvRDeANUDAv9y5AgcYdIod+lRTI6Gqpi0BO8x1qq9+Wg8EQPenTjCwekSMu9mm8MOn59AKavH2SuoQwi+UBBeLlTyyEJ+bYFH9uorkaO4kl0nfjfjj2PICHPuQ==,iv:OUvqDld+aq+Tp48uGt68/s+saEGf0hDoNlKTsQCAiN4=,tag:FecIjgOdeSp5Tbb+iPKb4Q==,type:str]
    ORG_ID: ENC[AES256_GCM,data:LxGlNDbW7lwP3JdeOBaBHZR7YXaIZJ8NRPYqhYJLOYDZXZNU,iv:OtJyTdqscLtZd67+C5ktyL3AZTp+ZYHZZ54sDJwJD8k=,tag:1tI3pA23w7vHci+VT/vL6A==,type:str]
    PROJ_ID: ENC[AES256_GCM,data:mMCKvZ9QoNL2VpJcg9TMtWKsurMbbXpeI7bq0ILGxTS9iNr0,iv:eUft1Z/FiNsJpjajXew6R2dg/B4bsKsdnGhwYCCtQq4=,tag:0PPZwcDjRUfu8BFjfF3/Fg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12v9uw8k6myrr49z9aq6jmcwa79aepu0p6p462nrv968qcae72pcspwldec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWVR4eGJYWUJ1V0F4Z2x0
            NW8wbFQrY1YxakY3RGtuQmozbFlyL0NqekVzCmZXNWFBdVg5RlBtdUp1dHVFWDlm
            ZVlGOXRjUGpJRm1rMzh1ck5BSVhadmsKLS0tIGVqeE5HUnZVczl4NkJmNEJ1NVoz
            KzRDbWFsVEpsalByQ1pKL2VsbHZuaTQKKQ+Ia4b12/kVhKvypUlf/riQuTQFh9zy
            T/Lp0g6o1eW7KoE+tFk9QgPGYLphyXn/iVNWpz+bMTXhcgFL0qTQZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-09T16:18:06Z"
    mac: ENC[AES256_GCM,data:ynjj0BIUvK1Ohj1tXO7xP5jwFYIpxmHDubfwu/KXJkAyoUmTLo5ZurKA/oIs1CBbgMgwvoU1MgO4ZZw0ZuyzijWtaexJ3EkytpMKIl6ncEFeLocyqx8aW0NDSn5Jhazc5MiEraMzqXS8C1mISoMyIcW7Rbjrm3SD8HvXvMHp1k4=,iv:YNvTzXOzWXsLDMylVx1ET5ndTDDY7ZBeFQ5oX4szAOY=,tag:f1ux0IY/gQvTlXAcxecMoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
