---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name external-dns-bind-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        EXTERNAL_DNS_RFC2136_TSIG_SECRET: "{{ .BIND_PI_RNDC_KEY }}"
  dataFrom:
  - extract:
      key: bind
