---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cloudflare-ddns
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      cloudflare-ddns:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/larivierec/cloudflare-ddns
              tag: main@sha256:9bdbd68dbf388e282ac75899775ced4de7507f6c37a0eef157e21cf9b1d3b3c3
            args:
              - --zone-name
              - ${SECRET_DOMAIN}
              - --record-name
              - ipv4.${SECRET_DOMAIN}
              - --provider
              - random
            env:
              ACCOUNT_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: cloudflare-ddns-secret
                    key: CLOUDFLARE_API_KEY
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health/alive
                    port: &healthPort 8080
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health/ready
                    port: *healthPort
            resources:
              requests:
                memory: 64Mi
                cpu: 10m
              limits:
                memory: 128Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 9000
          health:
            port: *healthPort
    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: health
            scheme: http
            path: /metrics
            interval: 30s
            scrapeTimeout: 30s
    ingress:
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal-utility.${SECRET_DOMAIN}
        hosts:
          - host: "ddns.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
