---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Flux-Kustomizations
  - ./cloudflared/ks.yaml
  - ./echo-server/ks.yaml
  - ./external-dns-cloudflare/ks.yaml
  - ./nginx-certificates/ks.yaml
  - ./nginx-ingress/ks.yaml
