---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plex-image-cleanup-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
  data:
    - secretKey: PLEX_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 5f4a73e9-dbaa-47bf-a5f2-ac6e00f706e3
        property: token
