apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-main
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:4fDPDBjGJd+bDq6XWw==,iv:aCQGLarnqqB8Kn/oNB7N51s2sMVKvlRTmam5cXFBDys=,tag:QyhWt48zxgH8fJmikPMQmg==,type:comment]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:idOub3IM8XJVAN3KvYId/C6MsBs/zHG6VQGC6bDsvnXGrPhe,iv:vtdEtuPNU4K8G11uGTVumPKQls4Enz+EjaS9sbKS+7E=,tag:B6b05KWzf1oNp9WZBJEJXg==,type:str]
    SVC_NGINX_INTERNAL: ENC[AES256_GCM,data:TyCwPUZSIIF7Xg==,iv:0pUtIxWfTzL/l1Ksw9W7/OpEoosIoj+7RBj8OkjGDkM=,tag:4xPusaS1Nc72il6Zl1M0Og==,type:str]
    SVC_NGINX_EXTERNAL: ENC[AES256_GCM,data:yD0KlDNJdHu23A==,iv:ufbiRzNHpGdtc59e8xxEWC2s/6lfI7pKPA/WorZ+ui0=,tag:YJaK+m3aT5k9ARXCsauzWw==,type:str]
    SVC_CPGO_ADDR: ENC[AES256_GCM,data:1ZEfa153U4NV5Q==,iv:Y6TDN76pCpEGLx03ZOO/0X6Z6rKuB+Kxk8/KXmS13K0=,tag:SwpJ/0qUK+j8Eq8lUuV2aQ==,type:str]
    SVC_PLEX_ADDR: ENC[AES256_GCM,data:1xZjw3xL5OJDQw==,iv:W8H53fUTHjDmhnyyZr+jcdUOakWdw3PRjVuLO/oDnBo=,tag:q/QaiVn1iQiFWOG0UOnIQw==,type:str]
    SVC_QBITTTORENT_ADDR: ENC[AES256_GCM,data:C1YY5DhkkwdO2A==,iv:SyHEO9JMb5ClhVm80Deq7desvahK8pYlWJtzb0g6pyY=,tag:GPFpWhdjJofBhd3khypV2A==,type:str]
    SVC_TAKOCRAFT_ADDR: ENC[AES256_GCM,data:FO629jc3FznVFQ==,iv:ggVburenvA0IOfOWr+RmGWUDntL369P4BjFMkJWEY8Y=,tag:MiX1TyqS1fahbZe93ETGwg==,type:str]
    SVC_PALWORLD_ADDR: ENC[AES256_GCM,data:sN51CLk0J5lueA==,iv:h/WiPB2ByiOjLLJwSegF0SXKklZazd81e0Qn//G8Wbk=,tag:Isi9IegNRCGbZ+nJfgC6Fw==,type:str]
    SVC_MINECRAFT_ADDR: ENC[AES256_GCM,data:f12BWnkvCdvjNg==,iv:gHfGEfHHQY9Rbu0uDls0sLdkje7UIQ4Mp+l5n33BJBA=,tag:NUo6kfMNYZQY9gRqZZN36g==,type:str]
    SVC_COREKEEPER_ADDR: ENC[AES256_GCM,data:fA4djsP75bTYlA==,iv:Kipkmlx+4AEkjmSjCdLKxSRRViAp0AP8SYgcyQImC0s=,tag:o7yurCyzgSHSnGmCHqZmAg==,type:str]
    #ENC[AES256_GCM,data:NYqIEJwguAGYzknS,iv:U0oZbqHMObZ+Wvx8ryQE8dlR0SG26wsfYV3F2F67H+w=,tag:oCJYngN4jrdWrQug82W9vQ==,type:comment]
    SECRET_NFS_DATA: ENC[AES256_GCM,data:RN+iTilzovBvmzeKmn8=,iv:9HOHKMlvI1tPJ0akJGHMYqrmhBWpHCthyhJEXuK/olk=,tag:NN30dHlw4WQVqulXe0/TUg==,type:str]
    SECRET_NFS_PAPERLESS: ENC[AES256_GCM,data:IjrRY8AXUBwvNUwl+2VK,iv:nlhXrqMAJ7Valrz8gheC7ZcznJTfNrnHS4uy75z/IC0=,tag:n0y2C1V9YpMNoHlcKNFuqQ==,type:str]
    SECRET_NFS_VOLSYNC: ENC[AES256_GCM,data:70s24/HdVnkvSrWHO2ofAstaDnaYbU/XCMssdg==,iv:4VoWUxB0m3PkR/hqmSzC2ThBOBZ/ECXu5ZbrmeO1jGI=,tag:/DZ4CFioDujyCuwsv1YSTg==,type:str]
    SECRET_NFS_POSTGRES: ENC[AES256_GCM,data:R35ymWjSAis2bvyU7aGN2K7xn5o9gMkD79vowWc=,iv:9ZQbMkqiklGYrk5pqkUiAKHuKCS28JgWynPBqFx1zbE=,tag:oicthoWKNN+mRo6H7VD6QA==,type:str]
    LATITUDE: ENC[AES256_GCM,data:+SFXV7JnoT1xX/1auwG7RA==,iv:Ojw+S3gtVIHN15uAveGVUsHFFfQogmx2uC0YcxNx+kM=,tag:l7m+O3NCMoqJCMVUgNz2Bw==,type:str]
    LONGITUDE: ENC[AES256_GCM,data:5JWin8qaaJh32nnHANsRsvs=,iv:jsepB8x8q/R97Be5ZxXpHGqUFuUaEv9r36CT4MaZSZs=,tag:/TeYa7lzjrksVuKLZw3mCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12v9uw8k6myrr49z9aq6jmcwa79aepu0p6p462nrv968qcae72pcspwldec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NWNTRmtma01pMFY3Ny93
            N2F5bTZFc0ZKYm5hWHp6bENndktxRXNBa1F3CnBNVXJldG9ZR0cwcXQrcjc5UTNu
            dlpJNEZ5eVhIdkwvRE5ubUNBQjhnWTQKLS0tIDhzRGZTdWFKak5PNmVnbG5hckl3
            Mml3TDJwa2tWTUV3d0piVTFJSFhhOEEKr0FLybpRsnIlbT55No+/qolp2GVAB1yD
            yeGYjULaarqScUazhWSnuzDcRj4X0MX8UDV5lc4OsGba9ymVbywDbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-12T16:42:57Z"
    mac: ENC[AES256_GCM,data:HHgkeHhkTITS6ZpWBDyQKnrssSDpPuzgo3TVZ7Fo7ok6Y9qRN8HPWAENvtHbyNfayMQde0cgj32xAgseYehEs2sjBTLYPj8h0YHXbba7YAFmWcqlASxnzWDtwiwLqTj/IKo/1gEZNagifFzHItqjDUrP/E1YlG3dcs9fg8NPxi4=,iv:/rJaJNOgQreAfLaFHR+A6qFIcQcRHHESt+eyj2xYOBo=,tag:d7LYAnAEUVJ2cyrycyGXPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
