apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-main
stringData:
    #ENC[AES256_GCM,data:4fDPDBjGJd+bDq6XWw==,iv:aCQGLarnqqB8Kn/oNB7N51s2sMVKvlRTmam5cXFBDys=,tag:QyhWt48zxgH8fJmikPMQmg==,type:comment]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:idOub3IM8XJVAN3KvYId/C6MsBs/zHG6VQGC6bDsvnXGrPhe,iv:vtdEtuPNU4K8G11uGTVumPKQls4Enz+EjaS9sbKS+7E=,tag:B6b05KWzf1oNp9WZBJEJXg==,type:str]
    SVC_NGINX_INTERNAL: ENC[AES256_GCM,data:TyCwPUZSIIF7Xg==,iv:0pUtIxWfTzL/l1Ksw9W7/OpEoosIoj+7RBj8OkjGDkM=,tag:4xPusaS1Nc72il6Zl1M0Og==,type:str]
    SVC_NGINX_EXTERNAL: ENC[AES256_GCM,data:yD0KlDNJdHu23A==,iv:ufbiRzNHpGdtc59e8xxEWC2s/6lfI7pKPA/WorZ+ui0=,tag:YJaK+m3aT5k9ARXCsauzWw==,type:str]
    SVC_CPGO_ADDR: ENC[AES256_GCM,data:1ZEfa153U4NV5Q==,iv:Y6TDN76pCpEGLx03ZOO/0X6Z6rKuB+Kxk8/KXmS13K0=,tag:SwpJ/0qUK+j8Eq8lUuV2aQ==,type:str]
    SVC_PLEX_ADDR: ENC[AES256_GCM,data:1xZjw3xL5OJDQw==,iv:W8H53fUTHjDmhnyyZr+jcdUOakWdw3PRjVuLO/oDnBo=,tag:q/QaiVn1iQiFWOG0UOnIQw==,type:str]
    SVC_QBITTTORENT_ADDR: ENC[AES256_GCM,data:C1YY5DhkkwdO2A==,iv:SyHEO9JMb5ClhVm80Deq7desvahK8pYlWJtzb0g6pyY=,tag:GPFpWhdjJofBhd3khypV2A==,type:str]
    SVC_TAKOCRAFT_ADDR: ENC[AES256_GCM,data:FO629jc3FznVFQ==,iv:ggVburenvA0IOfOWr+RmGWUDntL369P4BjFMkJWEY8Y=,tag:MiX1TyqS1fahbZe93ETGwg==,type:str]
    SVC_PALWORLD_ADDR: ENC[AES256_GCM,data:sN51CLk0J5lueA==,iv:h/WiPB2ByiOjLLJwSegF0SXKklZazd81e0Qn//G8Wbk=,tag:Isi9IegNRCGbZ+nJfgC6Fw==,type:str]
    SVC_MINECRAFT_ADDR: ENC[AES256_GCM,data:f12BWnkvCdvjNg==,iv:gHfGEfHHQY9Rbu0uDls0sLdkje7UIQ4Mp+l5n33BJBA=,tag:NUo6kfMNYZQY9gRqZZN36g==,type:str]
    SVC_COREKEEPER_ADDR: ENC[AES256_GCM,data:fA4djsP75bTYlA==,iv:Kipkmlx+4AEkjmSjCdLKxSRRViAp0AP8SYgcyQImC0s=,tag:o7yurCyzgSHSnGmCHqZmAg==,type:str]
    SVC_VRISING_ADDR: ENC[AES256_GCM,data:UMTb1QfKqeCiqA==,iv:OEI5tZKR6m0AgO8VqezIowzRUeqSI2qwSU34P5IqIXo=,tag:xMiAC6TEaYLb6o8i1jHlyw==,type:str]
    #ENC[AES256_GCM,data:NYqIEJwguAGYzknS,iv:U0oZbqHMObZ+Wvx8ryQE8dlR0SG26wsfYV3F2F67H+w=,tag:oCJYngN4jrdWrQug82W9vQ==,type:comment]
    SECRET_NFS_DATA: ENC[AES256_GCM,data:85DKixrSI8rproq1PmI=,iv:kvg70gJHchxhVQsjGInXA8V1bx1XzWjmICMhfquYZTg=,tag:f3dPXLWTKx7ApYucQtIe1w==,type:str]
    SECRET_NFS_PAPERLESS: ENC[AES256_GCM,data:U5zrsgH3/TED4QVZSzP2,iv:E1RB4QWwMpLYSGRJLOtC89Uat/7K3Hf/4m8feU2dcGw=,tag:TrZbkBC+3I7OUIb2VWGuWw==,type:str]
    SECRET_NFS_VOLSYNC: ENC[AES256_GCM,data:3NVs6XONZxR3Ze+uVX3gkmjpJIIlxU6Cd/kC0A==,iv:9SW3VVHHJKwloc4VrudeqZNmTiJMnQ4ozCiypt/bk4M=,tag:dUuQR8cAmKIgsVK0ywMEYA==,type:str]
    SECRET_NFS_POSTGRES: ENC[AES256_GCM,data:wsXmVzJZuz+YmB0RiEmNCBL3+eHC6sf/vWKYWUM=,iv:axtTCqsexrbVEemk2Xg29mWsB7I4rPzoErmfLx7YgVM=,tag:JL03bowQOFJnqrKzvB/MFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12v9uw8k6myrr49z9aq6jmcwa79aepu0p6p462nrv968qcae72pcspwldec
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NWNTRmtma01pMFY3Ny93
            N2F5bTZFc0ZKYm5hWHp6bENndktxRXNBa1F3CnBNVXJldG9ZR0cwcXQrcjc5UTNu
            dlpJNEZ5eVhIdkwvRE5ubUNBQjhnWTQKLS0tIDhzRGZTdWFKak5PNmVnbG5hckl3
            Mml3TDJwa2tWTUV3d0piVTFJSFhhOEEKr0FLybpRsnIlbT55No+/qolp2GVAB1yD
            yeGYjULaarqScUazhWSnuzDcRj4X0MX8UDV5lc4OsGba9ymVbywDbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-13T17:11:13Z"
    mac: ENC[AES256_GCM,data:fEWgwha/z/qiPsV0+Y+ETkvQU2cmM6XQM0qUnq56MBDVmqp+hFXOFy1V5M9mprPyzVu8UTEn2rl6lSN8gH1mHWF9QkgxsDyPFWBzAMzsXNgfMZ6oYyPnephrl6YQJnUnrWbxPWvjrHMDOeML4MPM7S7Rf5Fx3awxVilvxcGgtBs=,iv:9fLJPQTJ1FB0pBVDQqNiArE8DzWxzayWJ8O0VgPoQEY=,tag:HG2EmZ0sThhhf3v01puWkw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
