---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name bazarr-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # App
        BAZARR__API_KEY: "{{ .BAZARR_API_KEY }}"
        POSTGRES_ENABLED: "true"
        POSTGRES_DATABASE: &dbName bazarr
        POSTGRES_HOST: &dbHost postgres-rw.database.svc.cluster.local
        POSTGRES_USERNAME: &dbUser "{{ .POSTGRES_USERNAME }}"
        POSTGRES_PASSWORD: &dbPass "{{ .POSTGRES_PASSWORD }}"
        POSTGRES_PORT: "5432"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
  - extract:
      key: bazarr
  - extract:
      key: cloudnative-pg
