---
  # yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
  name: "Bulk Merge PRs"

  on:
    workflow_dispatch:
      inputs:
        dryRun:
          description: Dry Run
          default: "false"
          required: false
        labels:
          description: Labels
          default: "any"
          required: false

  jobs:
    bulk-merge-prs:
      name: Bulk Merge PRs
      runs-on: ubuntu-latest
      steps:
        - name: Get Secrets
          uses: 1password/load-secrets-action@v2
          with:
            export-env: true
          env:
            OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.ONEPASS_SA_TOKEN }}
            BOT_APP_ID: op://Kubernetes/github-bot/BOT_APP_ID
            BOT_APP_PRIVATE_KEY: op://Kubernetes/github-bot/BOT_APP_PRIVATE_KEY
            BOT_USERNAME: op://Kubernetes/github-bot/BOT_USERNAME

        - name: Generate Token
          uses: actions/create-github-app-token@v1
          id: app-token
          with:
            app-id: ${{ env.BOT_APP_ID }}
            private-key: ${{ env.BOT_APP_PRIVATE_KEY }}

        - name: Checkout
          uses: actions/checkout@v4
          with:
            token: ${{ steps.app-token.outputs.token }}

        - name: Merge
          env:
            GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          run: |
            args=()
            args+=(--app $BOT_USERNAME)
            args+=(--state open)
            if [ ${{ github.event.inputs.labels }} != "any" ]; then
                IFS=',' read -ra labels <<< ${{ github.event.inputs.labels }}
                for label in "${labels[@]}"; do
                    args+=(--label "${label}")
                done
            fi
            for id in $(gh pr list "${args[@]}" --jq '.[].number' --json number); do
                if [ ${{ github.event.inputs.dryRun }} = "true" ]; then
                    echo "Dry run: gh pr merge $id --squash"
                    continue
                fi
                gh pr merge "${id}" --squash
                sleep 2
            done
