---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Terraform Diff"

on:
  pull_request:
    branches: ["main"]
    paths: ["terraform/**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  changed-terraform:
    name: Changed Terraform
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-terraform.outputs.all_changed_and_modified_files }}
    steps:
      - name: Configure 1password
        uses: 1password/load-secrets-action/configure@v2
        with:
          service-account-token: ${{ secrets.ONEPASS_SA_TOKEN }}

      - name: Get Secrets
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          BOT_APP_ID: op://Kubernetes/github-bot/BOT_APP_ID
          BOT_APP_PRIVATE_KEY: op://Kubernetes/github-bot/BOT_APP_PRIVATE_KEY

      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ env.BOT_APP_ID }}
          private-key: ${{ env.BOT_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Get Changed Terraform
        id: changed-terraform
        uses: tj-actions/changed-files@v45
        with:
          files: terraform/**
          dir_names: true
          dir_names_max_depth: 2
          matrix: true

      - name: List All Changed Terraform
        run: echo ${{ steps.changed-terraform.outputs.all_changed_and_modified_files }}

  sync:
    name: Terraform Diff
    runs-on: ["gha-runner-scale-set"] #Backend is stored on local minio with no external ingress
    needs: ["changed-terraform"]
    strategy:
      matrix:
        paths: ${{ fromJSON(needs.changed-terraform.outputs.matrix) }}
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Configure 1password
        uses: 1password/load-secrets-action/configure@v2
        with:
          service-account-token: ${{ secrets.ONEPASS_SA_TOKEN }}

      - name: Get Secrets
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          BOT_APP_ID: op://Kubernetes/github-bot/BOT_APP_ID
          BOT_APP_PRIVATE_KEY: op://Kubernetes/github-bot/BOT_APP_PRIVATE_KEY
          MINIO_ACCESS_KEY: op://Kubernetes/minio/MINIO_ACCESS_KEY
          MINIO_SECRET_KEY: op://Kubernetes/minio/MINIO_SECRET_KEY

      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ env.BOT_APP_ID }}
          private-key: ${{ env.BOT_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Setup Workflow Tools
        shell: bash
        run: brew install node

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        id: fmt
        working-directory: ${{ matrix.paths }}
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        working-directory: ${{ matrix.paths }}
        env:
          AWS_ACCESS_KEY_ID: ${{ env.MINIO_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ env.MINIO_SECRET_KEY }}
        run: |
          terraform init \
            -backend-config="access_key=$AWS_ACCESS_KEY_ID" \
            -backend-config="secret_key=$AWS_SECRET_ACCESS_KEY"

      - name: Terraform Validate
        id: validate
        working-directory: ${{ matrix.paths }}
        run: terraform validate -no-color

      - name: Terraform Plan
        working-directory: ${{ matrix.paths }}
        run: terraform plan -lock=false -var "onepassword_sa_token=${{ secrets.ONEPASS_SA_TOKEN }}" -var "bw_access_token=${{ secrets.BW_ACCESS_TOKEN }}" -out .planfile | grep -v "Refreshing state...\|Reading...\|Read complete after"

      - name: Post PR comment
        if: github.event_name == 'pull_request'
        continue-on-error: true
        uses: borchero/terraform-plan-comment@v2
        with:
          token: ${{ steps.app-token.outputs.token }}
          header: "📝 Terraform Plan for ${{ matrix.paths }}"
          working-directory: ${{ matrix.paths }}
          planfile: .planfile
