# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.1/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: free-game-notifier
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      free-game-notifier:
        type: cronjob
        cronjob:
          schedule: '0 10 * 1-11 THU'
        containers: &container
          app:
            image:
              repository: ghcr.io/joryirving/free-game-notifier
              tag: 1.2.0@sha256:c8d433ed4567cb314c0fa0293041d20c2c56fdd43cd4ee5b6cc9639d1495f7f2
            env:
              TZ: "America/Edmonton"
              SEND_UPCOMING: false
            envFrom:
              - secretRef:
                  name: free-game-notifier
            resources:
              requests:
                cpu: 5m
              limits:
                memory: 128M
      dec:
        type: cronjob
        cronjob:
          schedule: '0 10 13-31 12 *'
        containers: *container
      jan:
        type: cronjob
        cronjob:
          schedule: '0 10 1-3 1 *'
        containers: *container
