# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: free-game-notifier
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        type: cronjob
        cronjob:
          schedule: '0 10 * 1-11 THU'
        containers: &container
          main:
            image:
              repository: ghcr.io/lildrunkensmurf/free-game-notifier
              tag: rolling
            env:
              TZ: "${TIMEZONE}"
              SEND_UPCOMING: false
            envFrom:
              - secretRef:
                  name: free-game-notifier
            resources:
              requests:
                cpu: 5m
              limits:
                memory: 128M
      dec:
        type: cronjob
        cronjob:
          schedule: '0 10 13-31 12 *'
        containers: *container
      jan:
        type: cronjob
        cronjob:
          schedule: '0 10 1-3 1 *'
        containers: *container
    service:
      main: &disabled
        enabled: false
    ingress:
      main: *disabled
