---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-repo3
spec:
  capacity:
    storage: 1Mi
  accessModes: ["ReadWriteMany"]
  nfs:
    server: voyager.internal
    path: ${SECRET_NFS_POSTGRES:=temp}
  mountOptions:
    - nfsvers=4.2
    - hard
    - noatime
    - nodiratime
    - rsize=131072
    - wsize=131072
    - nconnect=8
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-repo3 # this has to match the repo number in cluster.yaml
spec:
  accessModes:
    - ReadWriteMany
  volumeName: postgres-repo3
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
